package com.haoze.diting.ui.localization

/**
 * Localization entries for app settings, day/night mode, theme colors, transparency, wallpaper background, outbound proxy, and data cleanup.
 */
internal fun translateSettingsAndAppearanceExact(text: String): String? = when (text) {
    "底栏自定义" -> "Bottom bar customization"
    "自定义底栏按钮与显示顺序（2～4个）" -> "Customize bottom bar buttons and display order (2–4)"
    "底栏效果预览" -> "Bottom bar preview"
    "当前底栏预览" -> "Current bottom bar preview"
    "可点击上方底栏图标测试切换效果与高光" -> "Tap bottom bar icons to test transitions and specular highlights"
    "可拖动或点击上方底栏图标测试切换效果、高光与触感反馈" -> "Drag or tap bottom bar icons to test transitions, highlights, and haptic feedback"
    "底栏触感反馈" -> "Bottom bar haptic feedback"
    "拖动底栏或点击按钮时提供细腻触觉震动" -> "Provide subtle tactile vibration when dragging the bottom bar or clicking buttons"
    "项" -> "items"
    "所有页面均已添加到底栏" -> "All pages have been added to the bottom bar"
    "已选底栏按钮" -> "Selected bottom bar buttons"
    "可添加的页面" -> "Available pages to add"
    "底栏按钮数量限制在 2～4 个。您可在此自由添加、移除或调整底栏按钮的显示顺序。" -> "Bottom bar buttons are limited to 2–4. You can add, remove, or reorder buttons here."
    "底栏至少保留 2 个按钮" -> "At least 2 buttons must be kept"
    "底栏最多添加 4 个按钮" -> "At most 4 buttons can be added"
    "已恢复默认底栏配置" -> "Reset to default bottom bar configuration"
    "恢复默认" -> "Reset to default"
    "向上移动" -> "Move up"
    "向下移动" -> "Move down"
    "移除" -> "Remove"
    "添加" -> "Add"
    "暂无更多可添加的页面" -> "No more pages available to add"
    "个按钮" -> "buttons"
    "流量统计" -> "Traffic stats"
    "设置界面" -> "Settings screen"
    "核心服务开关与实时解析详情" -> "Core service toggle and real-time resolution details"
    "规则、工具与各功能统一入口" -> "Unified entry for rules, tools, and all features"
    "实时请求统计与规则拦截详情" -> "Real-time request statistics and rule interception details"
    "各应用流量消耗与实时速率统计" -> "App-level traffic consumption and real-time speed statistics"
    "DNS 测速、Ping 与网络诊断工具" -> "DNS speed test, Ping, and network diagnostics tools"
    "系统常规偏好与其它高级设置" -> "System general preferences and other advanced settings"
    "可选功能" -> "Optional features"
    "可选功能列表" -> "Optional features list"
    "隐藏功能" -> "Hidden features"
    "隐藏功能列表" -> "Hidden features list"
    "恢复全部显示" -> "Show all"
    "在功能中心显示" -> "Shown in Feature Hub"
    "已在功能中心隐藏" -> "Hidden from Feature Hub"
    "界面与设置" -> "Interface and settings"
    "数据与维护" -> "Data & maintenance"
    "自定义在功能中心显示的功能卡片。关闭开关将从功能中心隐藏该卡片，默认全部显示。隐藏仅调整界面展示，不会影响功能的后台运行与规则生效。" -> "Customize which feature cards appear in Feature Hub. Turning off a switch will hide that card from Feature Hub; all features are shown by default. Hiding a card only adjusts the UI and does not affect background service or filtering rules."
    "取消全选" -> "Deselect all"
    "自定义在功能中心中显示的功能卡片。勾选后即可在功能中心中显示，未勾选的功能将保持隐藏。" -> "Customize which feature cards appear in Feature Hub. Checked features will be shown; unchecked features will remain hidden."
    "解密并检查特定应用的 HTTP(S) 流量，支持域名与 URL 过滤" -> "Decrypt and inspect HTTP(S) traffic for selected apps with domain and URL filtering"
    "自定义日夜模式、主题色彩、组件透明度与软件壁纸背景" -> "Customize dark/light mode, accent color, opacity, and wallpaper background"
    "自定义在首页解析服务下拉列表中显示的服务商" -> "Customize providers shown in the home resolution service selector"
    "为特定应用单独指定 DNS 服务商或放行规则" -> "Specify independent DNS providers or allow rules for specific apps"
    "提供 DNS 查询、Ping 延迟测试与网络连通性诊断工具" -> "Provide DNS lookup, Ping latency testing, and network diagnostics tools"
    "统计各应用的网络连接数、上传与下载流量明细" -> "Statistics on network connections, upload and download traffic details for each app"
    "选择单一服务、智能选择、最快响应或依次尝试策略" -> "Select single provider, smart selection, fastest response, or fallback strategy"
    "删除缓存、日志或域名与地址过滤规则" -> "Delete cache, logs, or domain and address filtering rules"
    "配置大语言模型端点与密钥，为日志研判和网络诊断提供智能分析" -> "Configure LLM endpoints and keys to provide intelligent analysis for log evaluation and network diagnostics"
    "配置大语言模型接口与密钥，用于域名和网络流量分析" -> "Configure LLM endpoints and keys for domain and network traffic analysis"
    "配置大语言模型接口与密钥，用于日志和网络流量分析" -> "Configure LLM endpoints and keys for log and network traffic analysis"
    "AI 分析" -> "AI Analysis"
    "服务状态" -> "Service status"
    "启用 AI 分析" -> "Enable AI analysis"
    "开启后，可在 DNS 日志、请求日志、仪表盘等页面使用 AI 分析域名与网络流量" -> "Enable to use AI to analyze domains and network traffic in DNS logs, request logs, and dashboard"
    "详细设置" -> "Detailed settings"
    "AI 厂商管理" -> "AI Provider Management"
    "管理服务厂商、在线拉取模型与配置密钥" -> "Manage AI providers, pull model lists online, and configure keys"
    "我的厂商" -> "My Providers"
    "国内厂商" -> "Mainland Providers"
    "海外厂商" -> "Overseas Providers"
    "聚合与本地部署" -> "Aggregators & Local Deployment"
    "拉取模型列表" -> "Fetch model list"
    "接口与密钥" -> "Endpoints & Keys"
    "模型与预设" -> "Models & Presets"
    "参数与提示词" -> "Parameters & Prompt"
    "功能测试" -> "Functional test"
    "重置设置" -> "Reset settings"
    "域名安全分析" -> "Domain security analysis"
    "网络流量分析" -> "Network traffic analysis"
    "AI 网络分析" -> "AI network analysis"
    "AI 流量分析" -> "AI traffic analysis"
    "AI 分析该域名" -> "Analyze domain with AI"
    "未配置 API 密钥" -> "API key not configured"
    "AI 分析功能已关闭" -> "AI analysis is disabled"
    "正在进行 AI 分析..." -> "Performing AI analysis..."
    "分析失败" -> "Analysis failed"
    "分析结果已复制到剪贴板" -> "Analysis result copied to clipboard"
    "复制结果" -> "Copy result"
    "分析测试域名" -> "Analyze test domain"
    "分析当前网络" -> "Analyze current network"
    "系统提示词设定" -> "System prompt settings"
    "安全威胁分析" -> "Security threat analysis"
    "配置大语言模型端点与密钥，供外部或插件调用" -> "Configure large language model endpoints and keys for external or plugin access"
    "清除全部流量记录？" -> "Clear all traffic records?"
    "关闭“通知常驻”只会停止 VPN 未运行时的监控提醒。VPN 正在运行时，系统要求的前台服务通知会继续显示。" -> "Disabling “Persistent notification” stops monitoring reminders only while the VPN is not running. The required foreground-service notification remains while the VPN is running."
    "SOCKS5 通过 UDP ASSOCIATE 转发 UDP。代理应用本身将绕过 DITING，防止流量环路。" -> "SOCKS5 forwards UDP through UDP ASSOCIATE. The proxy app itself bypasses DITING to prevent traffic loops."
    "已忽略电池优化" -> "Battery optimization ignored"
    "删除壁纸" -> "Delete wallpaper"
    "确定删除这张已添加的壁纸吗？" -> "Delete this added wallpaper?"
    "重置所有新手引导" -> "Reset all onboarding guides"
    "数据清理" -> "Data cleanup"
    "出站代理" -> "Outbound proxy"
    "后台隐藏" -> "Hide in background"
    "IPv6 流量接管" -> "IPv6 traffic handling"
    "自动探测（推荐）" -> "Auto-detect (Recommended)"
    "根据物理网络是否具备公网 IPv6 地址及有效网关路由自动决策；在纯 IPv4 网络下自动关闭 IPv6 虚拟网卡，避免产生连接黑洞" -> "Automatically enable or disable based on physical network IPv6 availability and gateway routes; disables IPv6 on IPv4-only networks to avoid connection black holes"
    "始终开启" -> "Always enable"
    "虚拟网卡始终配置全局 IPv6 地址与路由" -> "Always configure global IPv6 address and routes on the virtual interface"
    "始终禁用" -> "Always disable"
    "仅配置 IPv4 虚拟网卡，强制所有双栈网站走 IPv4 隧道" -> "Configure only IPv4 on the virtual interface, forcing dual-stack sites through IPv4"
    "若在无 IPv6 的 Wi-Fi 下出现豆包、抖音等网站无法打开，请保持“自动探测”或设为“始终禁用”。修改后重新开启服务生效。" -> "If sites like Doubao or Douyin fail on Wi-Fi without IPv6, keep 'Auto-detect' or select 'Always disable'. Restart the service to apply."
    "通知常驻" -> "Persistent notification"
    "忽略电池优化" -> "Ignore battery optimizations"
    "日夜模式" -> "Light and dark mode"
    "主题色配置" -> "Accent color"
    "首页透明度" -> "Home-screen transparency"
    "分别调整首页按钮、选择框与文字的透明度" -> "Adjust the transparency of home buttons, selectors, and text"
    "首页句子" -> "Home messages"
    "通知栏文案" -> "Notification text"
    "分别设置 DNS 服务开启和关闭时的通知栏文案" -> "Set separate notification text for when the DNS service is enabled and disabled"
    "通知栏显示实时速率" -> "Show real-time speed in notification"
    "软件背景" -> "App background"
    "启用软件背景" -> "Enable app background"
    "已添加壁纸" -> "Added wallpapers"
    "主题色" -> "Accent color"
    "后台隐藏、通知常驻和电池设置" -> "Background hiding, persistent notifications, and battery settings"
    "将过滤后的流量转发到本地 SOCKS5 或 HTTP 代理" -> "Forward filtered traffic to a local SOCKS5 or HTTP proxy"
    "选择提供本地代理端口的应用。代理应用本身会绕过 DITING。" -> "Choose the app that provides the local proxy port. The proxy app itself bypasses DITING."
    "启用出站代理功能" -> "Enable outbound proxy"
    "代理应用" -> "Proxy app"
    "选择代理应用" -> "Choose proxy app"
    "正在连接出站代理" -> "Connecting to outbound proxy"
    "开启软件背景" -> "Enable app background"
    "关闭软件背景" -> "Disable app background"
    "使用系统壁纸的动态取色" -> "Use dynamic colors from the system wallpaper"
    "浅色模式" -> "Light mode"
    "深色模式" -> "Dark mode"
    "代理地址仅支持 127.0.0.1 或 ::1" -> "The proxy address must be 127.0.0.1 or ::1"
    "代理端口必须在 1 到 65535 之间" -> "The proxy port must be between 1 and 65535"
    "请选择提供本地代理端口的应用" -> "Choose the app that provides the local proxy port"
    "不能选择 DITING 自身作为代理应用" -> "DITING itself cannot be selected as the proxy app"
    "所选代理应用未安装" -> "The selected proxy app is not installed"
    "出站代理设置已保存" -> "Outbound proxy settings saved"
    "前往系统电池优化设置" -> "Open system battery optimization settings"
    "已重置所有新手引导" -> "All setup guides reset"
    "液态流体效果" -> "Liquid fluid effect"
    "设置悬浮底栏等组件的液态流体与磨砂折射效果" -> "Configure liquid fluid and frosted refraction effects for components like the bottom bar"
    "启用液态流体效果底栏" -> "Enable liquid fluid bottom bar"
    "为软件底部悬浮栏启用液态流体质感、磨砂光泽与流动光晕效果" -> "Enable liquid fluid texture, frosted sheen, and fluid glow for the floating bottom bar"
    "特别致谢开源项目 KernelSU (tiann/KernelSU) 及其优秀的液态流体与动态悬浮底栏交互设计与代码启发。" -> "Special thanks to open-source project KernelSU (tiann/KernelSU) for inspiring the liquid fluid aesthetic and dynamic floating bottom bar interaction."
    "液态玻璃效果" -> "Liquid glass effect"
    "设置悬浮底栏等组件的液态玻璃与磨砂折射效果" -> "Configure liquid glass and frosted refraction effects for components like the bottom bar"
    "启用液态玻璃效果底栏" -> "Enable liquid glass bottom bar"
    "为软件底部悬浮栏启用液态玻璃质感、磨砂光泽与流动光晕效果" -> "Enable liquid glass texture, frosted sheen, and fluid glow for the floating bottom bar"
    "特别致谢开源项目 KernelSU (tiann/KernelSU) 及其优秀的液态玻璃与动态悬浮底栏交互设计与代码启发。" -> "Special thanks to open-source project KernelSU (tiann/KernelSU) for inspiring the liquid glass aesthetic and dynamic floating bottom bar interaction."
    // Theme color names
    "鸢尾紫" -> "Iris Purple"
    "睡莲蓝" -> "Water Lily Blue"
    "池水青" -> "Pool Cyan"
    "柳叶绿" -> "Willow Green"
    "暮光赭" -> "Dusk Ochre"
    "罂粟红" -> "Poppy Red"
    "暮霞粉" -> "Sunset Pink"
    "麦穗金" -> "Wheat Gold"
    // Cache policy and resolution mode
    "跟随 DNS TTL" -> "Follow DNS TTL"
    "限制最长缓存时间" -> "Cap maximum TTL"
    "固定缓存时间" -> "Fixed TTL"
    "跟随系统" -> "Follow system"
    // Provider names
    "腾讯云" -> "Tencent Cloud"
    "字节跳动" -> "ByteDance"
    "自定义" -> "Custom"
    // Foreground/background and other
    "局域网" -> "Local network"
    "绕过局域网" -> "Bypass local network"
    "开启后局域网通信（如文件快传、投屏、NAS 访问等）直接走物理网络，不经过虚拟网卡" -> "When enabled, local network traffic (file quick transfer, screen casting, NAS access, etc.) goes directly through the physical network instead of the VPN interface"
    "若日常使用快传、LocalSend、投屏或访问局域网设备，建议保持开启。修改后重新开启服务生效。" -> "Keep this on if you regularly use quick transfer, LocalSend, screen casting, or access local network devices. Restart the service after changing."
    "前后台行为" -> "Foreground and background behavior"
    "后台隐藏、通知常驻、绕过局域网" -> "Background hiding, persistent notification, LAN bypass"
    "开启" -> "Enable"
    "未选择" -> "Not selected"
    "加载失败" -> "Load failed"
    "两项内容均可留空；留空后对应状态下首页不显示句子。" -> "Both fields can be left empty; the home page will not show a sentence in that state."
    "两项内容均可留空；留空后对应通知栏会使用默认状态文案。" -> "Both fields can be left empty; the notification will use the default status text in that case."
    // Outbound proxy status & errors
    "代理可用" -> "Proxy ready"
    "代理不可用" -> "Proxy unavailable"
    "出站代理不可用" -> "Outbound proxy unavailable"
    "连接失败" -> "Connection failed"
    "代理未启动或端口未开放" -> "Proxy not running or port not open"
    "连接代理超时" -> "Proxy connection timed out"
    "代理认证失败" -> "Proxy authentication failed"
    "代理不支持当前的认证方式" -> "Proxy does not support authentication method"
    "SOCKS5 代理不支持 UDP 转发" -> "SOCKS5 proxy does not support UDP associate"
    "无法连接到代理服务" -> "Cannot connect to proxy service"
    "HTTP 代理返回错误" -> "HTTP proxy returned error"
    "代理账号或密码过长" -> "Proxy username or password too long"
    "模式切换" -> "Mode Switch"
    "运行模式" -> "Operating Mode"
    "选择工作模式" -> "Select Operating Mode"
    "切换普通模式或服务器模式" -> "Switch between Normal mode and Server mode"
    "请根据您的使用场景选择运行模式" -> "Choose an operating mode based on your usage"
    "普通模式" -> "Normal Mode"
    "包含全量域名解析、黑白名单过滤、HTTPS 检查与网络管控能力" -> "Comprehensive domain resolution, allowlist/blocklist filtering, HTTPS inspection, and network controls"
    "轻量级纯 DNS 代理与解析加速，专注于低功耗防护" -> "Lightweight pure DNS proxy and resolution acceleration, focused on low-power protection"
    "推荐" -> "Recommended"
    "当前模式" -> "Current Mode"
    "当前选中" -> "Currently selected"
    "当前运行模式" -> "Current Running Mode"
    "运行中" -> "Active"
    "当前生效中" -> "Currently Active"
    "切换至此模式" -> "Switch to this mode"
    "全功能" -> "Full Featured"
    "极低功耗" -> "Ultra-low Power"
    "全功能网络管控与深度防护" -> "Full-featured network control & deep defense"
    "极低功耗纯 DNS 代理与解析加速" -> "Ultra-low power pure DNS proxy & resolution acceleration"
    "规则拦截与黑白名单" -> "Rule blocking & allow/blocklists"
    "HTTPS 报文级检查" -> "Packet-level HTTPS inspection"
    "应用分流与联网控制" -> "App routing & network access control"
    "详细流量与连接日志" -> "Detailed traffic & connection logs"
    "纯 DNS 报文代理" -> "Pure DNS packet proxy"
    "极低 CPU 与内存开销" -> "Minimal CPU & RAM overhead"
    "DoH / DoT 加密与竞速" -> "DoH / DoT encryption & racing"
    "独立轻量过滤规则" -> "Isolated lightweight filter rules"
    "模式特性对比" -> "Mode Capability Comparison"
    "接管范围" -> "Traffic Coverage"
    "整机全量网络流量" -> "All device network traffic"
    "仅 DNS 查询报文" -> "DNS query packets only"
    "规则与管控" -> "Rules & Filtering"
    "域名 / URL / 应用全面拦截" -> "Full domain, URL & app-level filtering"
    "纯域名与 Hosts 覆写" -> "Domain-only & Hosts rewrite"
    "HTTPS 检查" -> "HTTPS Inspection"
    "支持 (可选证书解密)" -> "Supported (optional decryption)"
    "不支持" -> "Not supported"
    "资源与功耗" -> "Resource & Battery"
    "标准 VPN 开销" -> "Standard VPN overhead"
    "极致低功耗与极低内存" -> "Ultra-low power & minimal memory"
    "确认切换运行模式" -> "Confirm Mode Switch"
    "当前已处于该模式" -> "Already in this mode"
    "切换模式将平滑重启核心网络服务，规则与配置已安全保留。" -> "Switching modes will smoothly restart the core network service; rules and settings are safely preserved."
    "切换模式将重启网络服务并进入对应主界面，您的规则与配置均安全保留。确认切换吗？" -> "Switching modes will restart the network service and switch to the target interface. Your rules and configurations will be safely preserved. Confirm switch?"
    "以此模式开启体验" -> "Get Started with this Mode"
    "切换为普通模式" -> "Switch to Normal Mode"
    "重新选择工作模式" -> "Re-select Work Mode"
    "谛听 · DITING" -> "DITING"
    "谛听 · 服务器模式" -> "DITING · Server Mode"
    "服务器模式" -> "Server Mode"
    "切换后将停止 DNS 服务并退出服务器模式。完整分流、黑白名单与应用管控等能力可在普通模式中按需开启。确认切换吗？" -> "Switching will stop the DNS service and exit server mode. Full traffic routing, allow/blocklists, and app network controls can be enabled there as needed. Confirm switch?"
    "确认切换" -> "Confirm Switch"
    "取消" -> "Cancel"
    "上游服务器" -> "Upstream Servers"
    "模式设置" -> "Mode Settings"
    "服务器模式运行中" -> "Server Mode Running"
    "正在启动服务..." -> "Starting service..."
    "正在停止服务..." -> "Stopping service..."
    "服务异常" -> "Service Error"
    "DNS 服务启动失败" -> "Failed to start DNS service"
    "DNS 服务启动失败，监听端口可能被占用" -> "Failed to start DNS service. The listen port may already be in use"
    "DNS 服务停止失败，请重试" -> "Failed to stop DNS service. Please try again"
    "DNS 服务更新失败，监听端口可能被占用" -> "Failed to update DNS service. The listen port may already be in use"
    "服务器模式已停止" -> "Server Mode Stopped"
    "总查询量" -> "Total Queries"
    "缓存命中" -> "Cache Hits"
    "已拦截" -> "Blocked"
    "平均时延" -> "Avg Latency"
    "运行时长" -> "Uptime"
    "服务器模式在本机提供局域网 DNS 解析服务，将其他设备的 DNS 指向本机即可使用；本机应用的查询不会自动经过该服务。" -> "Server mode serves LAN DNS resolution from this device. Point other devices' DNS at this device to use it; queries from this device itself do not automatically go through it."
    "模式管理" -> "Mode Management"
    "自定义上游" -> "Custom Upstreams"
    "添加自定义上游" -> "Add Custom Upstream"
    "编辑自定义上游" -> "Edit Custom Upstream"
    "删除自定义上游" -> "Delete Custom Upstream"
    "删除后相关解析将回退到默认上游。确认删除吗？" -> "After deletion, resolution falls back to the default upstream. Confirm delete?"
    "确认删除" -> "Confirm Delete"
    "编辑" -> "Edit"
    "上游名称" -> "Upstream Name"
    "解析地址" -> "Resolution Address"
    "DoH 解析地址" -> "DoH Address"
    "1.1.1.1 或 example.com" -> "1.1.1.1 or example.com"
    "支持 UDP / TCP / DoT / DoH 协议" -> "Supports UDP / TCP / DoT / DoH"
    "名称不能为空" -> "Name cannot be empty"
    "解析地址不能为空" -> "Address cannot be empty"
    "地址格式不正确" -> "Invalid address format"
    "端口必须为数字" -> "Port must be a number"
    "端口必须在 1-65535 之间" -> "Port must be between 1 and 65535"
    "DoH 地址必须以 https:// 开头" -> "DoH address must start with https://"
    "DoH 地址格式不正确" -> "Invalid DoH address format"
    "预设公共上游 DNS" -> "Preset Public Upstream DNS"
    "代理与解析设置" -> "Proxy & Resolution Settings"
    "DNS 缓存" -> "DNS Cache"
    "启用本地 DNS 记录缓存，加速重复域名查询" -> "Enable local DNS record cache to accelerate repeated domain lookups"
    "恶意域名过滤" -> "Malicious Domain Filtering"
    "与普通模式共用屏蔽规则，命中后按拦截策略返回" -> "Shares block rules with Normal mode; matching domains receive the configured block response"
    "本地监听端口" -> "Local Listen Port"
    "DNS 服务在本机监听的端口，默认 1053" -> "Port the DNS service listens on locally; defaults to 1053"
    "范围 1024-65535，默认 1053" -> "Range 1024-65535, default 1053"
    "保存" -> "Save"
    "后台稳定性" -> "Background Stability"
    "保持 DNS 服务在后台稳定运行" -> "Keep the DNS service running stably in the background"
    "数据与重置" -> "Data & Reset"
    "重置运行统计" -> "Reset Runtime Statistics"
    "清空本次运行的统计数据" -> "Clear all statistics of this run"
    "将清空本次运行的全部统计数据，确认继续吗？" -> "This will clear all statistics of the current run. Continue?"
    "确认重置" -> "Confirm Reset"
    "启用完整分流、黑白名单与应用网络管控" -> "Enable full traffic routing, allow/blocklists, and app network control"
    "浏览所有工作模式详情并重新选择" -> "View all work mode details and re-select"
    "显示服务器模式的运行状态" -> "Show the running status of server mode"
    "停止" -> "Stop"
    "启动中" -> "Starting"
    "当前上游" -> "Active Upstream"
    "谛听 · 服务器模式运行中" -> "DITING · Server Mode Running"
    "轻量" -> "Lightweight"
    "阿里 DNS" -> "Ali DNS"
    "腾讯 DNSPod" -> "Tencent DNSPod"
    "Cloudflare DNS" -> "Cloudflare DNS"
    "Google Public DNS" -> "Google Public DNS"
    "Quad9 DNS" -> "Quad9 DNS"
    "阿里 DNS (DoH)" -> "Ali DNS (DoH)"
    "Cloudflare (DoH)" -> "Cloudflare (DoH)"
    "阿里 DNS (DoT)" -> "Ali DNS (DoT)"
    "Cloudflare (DoT)" -> "Cloudflare (DoT)"
    "阿里巴巴公共 DNS，国内解析低时延" -> "Alibaba public DNS with low latency in mainland China"
    "腾讯云公共解析，节点覆盖广" -> "Tencent Cloud public resolution with broad node coverage"
    "全球快速且隐私友好的 DNS 服务" -> "Fast and privacy-friendly global DNS"
    "Google 全球公共 DNS 解析服务" -> "Google's global public DNS resolution service"
    "内置恶意域名安全拦截与隐私保护" -> "Built-in malicious-domain blocking and privacy protection"
    "基于 HTTPS 的加密 DNS 解析" -> "Encrypted DNS resolution over HTTPS"
    "Cloudflare 1.1.1.1 加密 DNS 查询" -> "Encrypted DNS queries via Cloudflare 1.1.1.1"
    "基于 TLS 的加密 DNS 解析" -> "Encrypted DNS resolution over TLS"
    "360 安全 DNS，提供基础安全防护" -> "360 Secure DNS providing basic security protection"
    "北京联盛 OneDNS，拦截恶意网站" -> "Beijing Liansheng OneDNS, blocking malicious websites"
    "阿里巴巴公共 DNS，基于 HTTPS 的加密解析" -> "Alibaba public DNS, encrypted resolution over HTTPS"
    "腾讯云公共解析，基于 HTTPS 的加密解析" -> "Tencent Cloud public resolution, encrypted resolution over HTTPS"
    "360 安全 DNS，基于 HTTPS 的加密解析" -> "360 Secure DNS, encrypted resolution over HTTPS"
    "OneDNS 安全解析，基于 HTTPS 的加密解析" -> "OneDNS secure resolution, encrypted resolution over HTTPS"
    "Google 公共 DNS，基于 HTTPS 的加密解析" -> "Google public DNS, encrypted resolution over HTTPS"
    "阿里巴巴公共 DNS，基于 TLS 的加密解析" -> "Alibaba public DNS, encrypted resolution over TLS"
    "腾讯云公共解析，基于 TLS 的加密解析" -> "Tencent Cloud public resolution, encrypted resolution over TLS"
    "360 安全 DNS，基于 TLS 的加密解析" -> "360 Secure DNS, encrypted resolution over TLS"
    "OneDNS 安全解析，基于 TLS 的加密解析" -> "OneDNS secure resolution, encrypted resolution over TLS"
    "Google 公共 DNS，基于 TLS 的加密解析" -> "Google public DNS, encrypted resolution over TLS"
    "以下操作会立即删除本机数据，删除后无法恢复。重要规则或配置请在执行前备份。" -> "The following actions permanently delete local data. Back up important rules or configurations before proceeding."
    "权重数据" -> "Weight data"
    "规则与订阅" -> "Rules and subscriptions"
    "存储与安全" -> "Storage and security"
    "引导与重置" -> "Guides and reset"
    "删除请求日志" -> "Delete request logs"
    "清除 DNS、HTTP 请求日志、竞速统计及 Bootstrap 解析日志" -> "Clear DNS and HTTP request logs, race statistics, and Bootstrap resolution logs"
    "删除流量统计" -> "Delete traffic statistics"
    "清除所有应用的历史流量统计记录与实时统计状态" -> "Clear all app historical traffic statistics and real-time counter states"
    "删除崩溃日志" -> "Delete crash logs"
    "清除本地保存的所有 Java 与 Native 异常崩溃日志" -> "Clear all saved Java and Native exception crash logs"
    "删除 DNS 缓存" -> "Delete DNS cache"
    "移除已缓存的解析结果，下次访问会重新查询" -> "Remove cached resolution results; domains will be queried again on next access"
    "恢复 DNS 默认权重" -> "Restore default DNS weights"
    "清除智能选择的健康样本，让它重新按默认权重分配流量" -> "Clear smart selection health samples to reassign traffic by default weights"
    "清除 Bootstrap DNS 解析健康样本，重新按默认权重选择" -> "Clear Bootstrap resolution health samples to choose servers by default weights"
    "删除全部域名规则" -> "Delete all domain rules"
    "清除域名屏蔽、白名单、IPv4/IPv6 覆写及对应订阅，恢复预设白名单" -> "Clear domain block, allow, IPv4/IPv6 override rules, and subscriptions; restore default preset whitelist"
    "删除全部地址规则" -> "Delete all address rules"
    "清除 URL 屏蔽、放行和 CNAME 覆写规则，不影响域名规则" -> "Clear URL block, allow, and CNAME override rules; domain rules are not affected"
    "删除全部规则订阅" -> "Delete all rule subscriptions"
    "清除所有网络与本地规则订阅、订阅分组及自动更新任务" -> "Clear all network and local rule subscriptions, groups, and auto-update tasks"
    "重置应用控制名单" -> "Reset app control lists"
    "清空分应用排除、禁止联网应用、应用白名单及抓包名单" -> "Clear excluded apps, blocked apps, app allowlists, and inspection app lists"
    "重置出站代理配置" -> "Reset outbound proxy configuration"
    "清空出站代理协议、服务器与鉴权信息，恢复直连" -> "Clear outbound proxy protocol, server, and credentials; restore direct connection"
    "重置 HTTPS 抓包证书" -> "Reset HTTPS inspection certificate"
    "清除本地生成的 MITM CA 根证书与私钥" -> "Clear locally generated MITM CA root certificate and private key"
    "清理下载与临时缓存" -> "Clear downloads and temporary cache"
    "删除更新安装包、下载临时文件及应用临时缓存" -> "Delete update APK packages, download temp files, and app caches"
    "清除自定义背景缓存" -> "Clear custom background cache"
    "清除已配置的自定义壁纸图片缓存及路径记录，恢复默认背景" -> "Clear custom wallpaper image cache and saved paths; restore default background"
    "让所有首次进入说明再次显示，需要重新同意使用协议" -> "Show all introductory guides again; requires accepting user agreement upon restart"
    "清理全部本地数据" -> "Clear all local data"
    "深度清空所有日志、缓存、规则、订阅、证书与配置，应用将退出" -> "Completely clear all logs, caches, rules, subscriptions, certificates, and config; app will exit"
    "确定要清除所有应用的历史流量统计记录与实时统计状态吗？" -> "Clear all app historical traffic statistics and real-time counter states?"
    "确定要删除所有本地崩溃日志和崩溃统计状态吗？" -> "Delete all local crash logs and crash counter state?"
    "确定要删除所有规则订阅吗？所有订阅链接、分组与订阅导入的规则都会被移除，手动添加的规则不受影响。" -> "Delete all rule subscriptions? All subscription URLs, groups, and imported rules will be removed; manual rules are not affected."
    "确定要重置所有应用控制名单吗？分应用代理排除、禁止联网应用、应用独立白名单以及 HTTP/HTTPS 抓包应用配置都将被清空并恢复默认。" -> "Reset all app control lists? Excluded apps, blocked apps, app allowlists, and HTTP/HTTPS inspection configurations will be cleared and reset to defaults."
    "确定要重置出站代理配置吗？出站代理将被禁用，服务器地址、端口及账号密码将被清除。" -> "Reset outbound proxy configuration? Outbound proxy will be disabled, and server address, port, and credentials will be cleared."
    "确定要清除本地生成的 HTTPS 抓包 CA 证书和私钥吗？如果系统已安装此证书，清除后需重新生成并导入系统方可继续解密抓包。" -> "Clear the locally generated HTTPS inspection CA certificate and private key? If already installed in the system, you must regenerate and re-import it to inspect traffic."
    "确定要删除下载的更新安装包和临时缓存文件吗？" -> "Delete downloaded update APK packages and temporary cache files?"
    "确定要清除自定义壁纸缓存并恢复默认外观背景吗？" -> "Clear custom wallpaper cache and restore default appearance background?"
    "确定要执行全面数据清理吗？将依次清理所有日志、流量统计、崩溃记录、DNS 缓存、服务商权重、域名及地址规则、规则订阅、临时缓存及抓包证书。所有自定义配置与规则将被清空，新手引导也将重置，操作完成后应用将退出。" -> "Execute full data cleanup? This will sequentially clean all logs, traffic stats, crash reports, DNS cache, provider weights, domain and address rules, subscriptions, temporary cache, and CA certificate. All custom rules and settings will be reset, onboarding will reset, and the app will exit."
    "清除 DNS 请求日志、竞速统计及 Bootstrap 解析日志" -> "Clear DNS request logs, race statistics, and Bootstrap resolution logs"
    "确定要删除所有 DNS 请求日志、竞速统计和 Bootstrap DNS 解析统计吗？" -> "Delete all DNS request logs, race statistics, and Bootstrap resolution statistics?"
    "清除域名屏蔽、白名单及对应订阅，恢复预设白名单" -> "Clear domain block, allow rules, and subscriptions; restore default preset whitelist"
    "确定要删除全部域名规则吗？域名屏蔽、白名单及对应订阅都会被移除。" -> "Delete all domain rules? Domain block, allow rules, and subscriptions will be removed."
    "深度清空所有日志、缓存、规则、订阅与配置，应用将退出" -> "Completely clear all logs, caches, rules, subscriptions, and config; app will exit"
    "确定要执行全面数据清理吗？将依次清理所有日志、崩溃记录、DNS 缓存、服务商权重、域名规则、规则订阅及临时缓存。所有自定义配置与规则将被清空，新手引导也将重置，操作完成后应用将退出。" -> "Execute full data cleanup? This will sequentially clean all logs, crash reports, DNS cache, provider weights, domain rules, subscriptions, and temporary cache. All custom rules and settings will be reset, onboarding will reset, and the app will exit."
    "确定要重置所有应用设置新手引导和首次使用协议吗？这不会删除任何配置、规则、缓存或日志。操作完成后应用将退出；下次打开时需要重新同意使用协议，所有新手引导也会再次显示。" -> "Reset all app introductory guides and user agreement? This will not delete any configurations, rules, caches, or logs. The app will exit after this operation; you will need to accept the agreement again on next launch, and introductory guides will be shown again."
    else -> null
}


internal fun translateSettingsAndAppearancePattern(text: String): String? = when {
    text.startsWith("出站代理不可用 · ") -> {
        val suffix = text.removePrefix("出站代理不可用 · ")
        "Outbound proxy unavailable · ${translateSettingsAndAppearanceExact(suffix) ?: suffix}"
    }
    text.startsWith("代理不可用 · ") -> {
        val suffix = text.removePrefix("代理不可用 · ")
        "Proxy unavailable · ${translateSettingsAndAppearanceExact(suffix) ?: suffix}"
    }
    text.startsWith("关闭“通知常驻”") -> "Disabling persistent notifications only stops monitoring reminders while the VPN is not running. The required foreground-service notification remains visible while the VPN is running."
    else -> null
}
