package com.haoze.dnssr.ui.localization

/**
 * 通用 UI 控件、基础动作、确认弹窗、时间与数量单位等基础本地化词条。
 */
internal fun translateCommonExact(text: String): String? = when (text) {
    "同意并继续" -> "Agree and continue"
    "不同意并退出" -> "Decline and exit"
    "今日" -> "Today"
    "本周" -> "This Week"
    "本月" -> "This Month"
    "全部历史" -> "All History"
    "实时速率" -> "Realtime Speed"
    "缓存命中的 DNS 请求不会触发实际竞速，因此不计入这里的统计。" -> "DNS requests served from cache do not trigger an actual race and are excluded from these statistics."
    "移除已缓存的解析结果，下次访问会重新查询" -> "Remove cached resolution results; the next visit will query again"
    "未选择目标应用，仅保留 DNS 过滤" -> "No target apps selected; keeps DNS filtering only"
    "目标应用" -> "Target apps"
    "未选择任何应用" -> "No apps selected"
    "未安装或未验证，点击配置" -> "Not installed or verified; tap to configure"
    "尝试检查 HTTP/3" -> "Try to inspect HTTP/3"
    "阻止检查应用使用加密 DNS" -> "Block inspected apps from using encrypted DNS"
    "排除后，应用将使用系统 DNS，不参与本应用的过滤、缓存、日志和统计。" -> "Excluded apps use the system DNS and do not participate in this app's filtering, caching, logging, or statistics."
    "你的每一笔支持都会用于" -> "Your support helps us"
    "持续开发新功能" -> "Continue developing new features"
    "修复 Bug" -> "Fix bugs"
    "购买词元" -> "Purchase token credits"
    "即使不捐赠，也欢迎" -> "Even without donating, you are welcome to"
    "数据管理" -> "Data management"
    "备份与迁移" -> "Backup & Migration"
    "在不同设备之间安全迁移谛听的应用配置，或导出/导入本地规则与订阅文件。" -> "Safely transfer DNSSR configurations between devices, or export/import local rules and subscription files."
    "应用配置" -> "App configuration"
    "导入应用配置" -> "Import Application Config"
    "复制明细" -> "Copy Details"
    "已复制明细日志" -> "Details copied to clipboard"
    "正在处理，请稍候..." -> "Processing, please wait..."
    "配置文件操作" -> "Configuration file operations"
    "导出配置 (JSON)" -> "Export configuration (JSON)"
    "导入配置 (JSON)" -> "Import configuration (JSON)"
    "从本地 JSON 合并配置，自动跳过本机已存在项目" -> "Merge configurations from local JSON, skipping existing local items automatically"
    "配置文件仅包含所选的自定义配置与分流规则，不包含历史日志、DNS 缓存和已下载的域名规则。" -> "The configuration file only includes selected custom configurations and routing rules, excluding history logs, DNS cache, and downloaded domain rules."
    "导出的配置文件可能包含个人自定义 DNS 节点与规则配置；本地导入的规则文件将作为不可自动更新的本地订阅保存在本机。" -> "Exported configurations may contain personal custom DNS endpoints and rules. Imported local rule files are saved as non-updatable subscriptions."
    "导出 CSV" -> "Export CSV"
    "选择状态" -> "Choose status"
    "请求解析或处理失败" -> "Request resolution or processing failed"
    "未取得 authority" -> "Authority unavailable"
    "管理服务..." -> "Manage providers..."
    "服务显示..." -> "Provider visibility..."
    "连接中" -> "Connecting"
    "断开" -> "Disconnect"
    "仅记录拦截与错误" -> "Recording blocked and failed requests only"
    "缓存命中" -> "Cache hits"
    "竞速请求" -> "Race requests"
    "失败" -> "Failed"
    "缓存" -> "Cache"
    "竞速成功率" -> "Race success rate"
    "拦截率" -> "Block rate"
    "缓存率" -> "Cache rate"
    "缓存热点" -> "Cache hotspots"
    "竞速胜出" -> "Race winners"
    "重点请求概览" -> "Priority request overview"
    "最近重点请求" -> "Recent priority requests"
    "当前有效条目" -> "Current valid entries"
    "VPN 运行且应用在后台时显示悬浮球，点击查看最近请求" -> "Show a floating button while the VPN runs in the background; tap it to view recent requests"
    "允许应用在后台稳定运行" -> "Allow the app to run reliably in the background"
    "已忽略" -> "Ignored"
    "可设置 1 至 168 小时" -> "Set between 1 and 168 hours"
    "请输入 1 至 168 之间的小时数" -> "Enter a number of hours between 1 and 168"
    "显示该类型的全部服务" -> "Show all services of this type"
    "不显示该类型的服务" -> "Do not show services of this type"
    "保存通过、拦截和错误请求" -> "Save passed, blocked, and failed requests"
    "减少数据库写入，同时保留关键记录" -> "Reduce database writes while keeping important records"
    "正在加载统计数据" -> "Loading statistics"
    "正在加载" -> "Loading"
    "自动清理时间" -> "Automatic cleanup interval"
    "选择检查应用" -> "Select apps to inspect"
    "同一域名的所有记录类型合并计数" -> "Count all record types for the same domain together"
    "关闭后每次解析都会请求上游 DNS" -> "When disabled, every resolution requests the upstream DNS"
    "已过期" -> "Expired"
    "请求次数" -> "Request count"
    "统计窗口（秒）" -> "Statistics window (seconds)"
    "记录与统计" -> "Records and statistics"
    "查看 DNS 与 HTTPS 请求和处理结果" -> "View DNS and HTTPS requests and processing results"
    "查看、搜索或清理已缓存的 DNS 结果" -> "View, search, or clear cached DNS results"
    "竞速解析" -> "Race resolution"
    "查看 DNS 服务地址的解析情况" -> "View resolution results for DNS service addresses"
    "维护工具" -> "Maintenance tools"
    "检查范围" -> "Inspection scope"
    "协议与兼容性" -> "Protocols and compatibility"
    "关闭搜索" -> "Close search"
    "建议使用“标准”。档位会自动设置最长 TTL、最短 TTL 和解析失败兜底时间，不再需要手动填写秒数。" -> "Standard is recommended. Presets configure the maximum TTL, minimum TTL, and fallback time for failed resolutions, so seconds do not need to be entered manually."
    "运行数据" -> "Runtime data"
    "用户数据" -> "User data"
    "我知道了" -> "Got it"
    "动态参数" -> "Dynamic parameters"
    "A 返回 0.0.0.0，AAAA 返回 ::，其他类型返回空结果" -> "Return 0.0.0.0 for A, :: for AAAA, and an empty result for other types"
    "重新验证" -> "Verify again"
    "尚未完成" -> "Not completed"
    "立即重置" -> "Reset now"
    "新增" -> "Add"
    "名称（可选）" -> "Name (optional)"
    "IP 地址" -> "IP address"
    "搜索应用或包名" -> "Search apps or package names"
    "已导入 HTTPS" -> "Imported to HTTPS"
    "请求预览" -> "Request preview"
    "DNS 过滤" -> "DNS filtering"
    "本地文件" -> "Local file"
    "拦截策略" -> "Blocking policy"
    "拦截响应" -> "Block response"
    "输入要屏蔽的域名，如 example.com" -> "Enter a domain to block, e.g. example.com"
    "输入要放行的域名，如 example.com" -> "Enter a domain to allow, e.g. example.com"
    "正在验证系统凭据…" -> "Verifying system credentials..."
    "已验证" -> "Verified"
    "未验证" -> "Not verified"
    "安装与查看" -> "Install and inspect"
    "安装与卸载指南" -> "Installation and removal guide"
    "已安装" -> "Installed"
    "未安装" -> "Not installed"
    "稍后完成" -> "Do later"
    "重新生成" -> "Regenerate"
    "设置配置" -> "Configuration transfer"
    "导出内容" -> "Export contents"
    "名称、协议和解析地址" -> "Names, protocols, and resolution addresses"
    "名称、IP 和启用状态" -> "Names, IPs, and enabled states"
    "使用系统 DNS 的应用包名" -> "Package names of apps using system DNS"
    "配置文件" -> "Configuration file"
    "导出配置" -> "Export configuration"
    "导入配置" -> "Import configuration"
    "正在准备" -> "Preparing"
    "时间范围" -> "Time range"
    "统计" -> "Statistics"
    "概览" -> "Overview"
    "整体表现" -> "Overall performance"
    "全局开关" -> "Global switch"
    "所选应用只能连接其白名单域名解析出的 IP。直连 IP、局域网、加密 DNS 和其他连接会被阻止；共享 CDN IP 在 DNS TTL 内可能承载其他站点。" -> "Selected apps can connect only to IPs resolved from their allowlisted domains. Direct IPs, LAN, encrypted DNS, and other connections are blocked; a shared CDN IP may serve other sites during its DNS TTL."
    "请先添加至少一个白名单域名" -> "Add at least one allowlisted domain first"
    "这些应用仅可访问白名单域名" -> "These apps can access only allowlisted domains"
    "白名单域名" -> "Allowlisted domains"
    "域名，如 example.com" -> "Domain, e.g. example.com"
    "请输入有效域名" -> "Enter a valid domain"
    "尚未选择应用；开启后仅保留 DNS 过滤" -> "No apps selected; enabling this keeps DNS filtering only"
    "通过本机 VPN 按 UID 阻止所选应用的全部网络连接。共享同一 UID 的应用会一并受影响。" -> "Block all network connections for selected apps by UID through the local VPN. Apps sharing the same UID are affected together."
    "选择需要阻止联网的应用" -> "Select apps whose network access should be blocked"
    "服务开启时，所选应用的全部网络连接将被阻止。共享同一 UID 的应用会一并受影响。" -> "When the service is enabled, all network connections for selected apps are blocked. Apps sharing the same UID are affected together."
    "继续" -> "Continue"
    "暂不允许" -> "Not now"
    "允许访问" -> "Allow access"
    "反选" -> "Invert selection"
    "过滤" -> "Filter"
    "排序" -> "Sort"
    "取消" -> "Cancel"
    "删除" -> "Delete"
    "确定" -> "OK"
    "添加" -> "Add"
    "DNS 服务开启时" -> "When DNS service is enabled"
    "DNS 服务关闭时" -> "When DNS service is disabled"
    "暂无竞速数据" -> "No race data"
    "暂无拦截或错误记录" -> "No blocked or error records"
    "搜索请求" -> "Search requests"
    "正在加载…" -> "Loading..."
    "筛选请求状态" -> "Filter request status"
    "处理域名" -> "Manage domain"
    "正在导入" -> "Importing"
    "知道了" -> "Got it"
    "清除" -> "Clear"
    "解散分组" -> "Dissolve group"
    "解散" -> "Dissolve"
    "要屏蔽的域名，如 example.com" -> "Domain to block, e.g. example.com"
    "要放行的域名，如 example.com" -> "Domain to allow, e.g. example.com"
    "请输入要屏蔽的域名" -> "Enter a domain to block"
    "请输入要放行的域名" -> "Enter a domain to allow"
    "域名或模式，如 example.com 或 *-analytics.google.com" -> "Domain or pattern, e.g. example.com or *-analytics.google.com"
    "添加失败" -> "Add failed"
    "按协议、主机和路径前缀匹配，忽略查询参数" -> "Matches protocol, host, and path prefix; query parameters are ignored"
    "跳转到页面" -> "Go to page"
    "页码" -> "Page number"
    "跳转" -> "Go"
    "上一页" -> "Previous page"
    "下一页" -> "Next page"
    "手动添加" -> "Manually added"
    "已选中" -> "Selected"
    "当前模式" -> "Current mode"
    "模式配置" -> "Mode configuration"
    "查询服务" -> "Query provider"
    "主" -> "Primary"
    "长按并拖动调整顺序" -> "Long-press and drag to reorder"
    "按设置顺序查询，前一个失败后切换下一个服务" -> "Query providers in order and switch to the next after a failure"
    "查询耗时结果" -> "Query latency results"
    "测试查询耗时" -> "Test query latency"
    "DNS 提供商健康情况" -> "DNS provider health"
    "刷新" -> "Refresh"
    "未参与" -> "Not participating"
    "打开最近请求" -> "Open recent requests"
    "最近请求" -> "Recent requests"
    "小" -> "Small"
    "中" -> "Medium"
    "大" -> "Large"
    "正在加载日志…" -> "Loading logs..."
    "拦截" -> "Blocked"
    "全部" -> "All"
    "放行" -> "Allowed"
    "直连" -> "Direct"
    "已放行" -> "Allowed"
    "已拦截" -> "Blocked"
    "无效请求" -> "Invalid request"
    "错误" -> "Error"
    "重写" -> "Rewritten"
    "绕过" -> "Bypassed"
    "未取得请求地址" -> "Request address unavailable"
    "小时" -> "Hours"
    "暂无分组" -> "No groups"
    "Go 隧道已启用" -> "Go tunnel enabled"
    "确认并继续" -> "Confirm and continue"
    "解析设置" -> "Resolution"
    "性能优化" -> "Performance"
    "运行行为" -> "Behavior"
    "外观" -> "Appearance"
    "缓存设置" -> "Cache settings"
    "日志模式" -> "Log mode"
    "导入与导出" -> "Import and export"
    "外观设置" -> "Appearance settings"
    "固定响应" -> "Fixed response"
    "动态策略" -> "Dynamic policy"
    "启用动态策略" -> "Enable dynamic policy"
    "后台" -> "Background"
    "开启后隐藏最近任务卡片" -> "Hide the recent-task card"
    "VPN 未运行时在通知栏常驻提醒，不影响 VPN 运行中的连接通知" -> "Keep a reminder in the notification shade while the VPN is stopped; this does not affect connection notifications while it runs"
    "当前的地址并不符合要求" -> "The current address is invalid"
    "通过" -> "Passed"
    "电池" -> "Battery"
    "界面显示" -> "Interface"
    "选择应用使用的浅色或深色外观" -> "Choose the light or dark appearance used by the app"
    "选择应用界面的强调色" -> "Choose the accent color used by the app interface"
    "首页内容" -> "Home content"
    "分别设置 DNS 服务开启和关闭时的句子" -> "Set separate messages for when the DNS service is enabled and disabled"
    "服务开启时在通知栏中实时显示上传和下载速率" -> "Show real-time upload and download speeds in notification when service is running"
    "背景与动效" -> "Background and animation"
    "选取手机图片作为应用背景" -> "Choose a photo on the phone as the app background"
    "兼容功能" -> "Compatibility"
    "切换桌面入口图标的样式" -> "Change the style of the launcher icon"
    "选择首页日志按钮打开的页面" -> "Choose the page opened by the home Logs button"
    "开启后仅将桌面入口图标切换为旧版样式" -> "Only the launcher icon changes to the legacy style"
    "自定义背景" -> "Custom background"
    "添加图片" -> "Add image"
    "交互组件" -> "Interaction components"
    "文字" -> "Text"
    "主题" -> "Theme"
    "缓存已解析的域名，减少重复查询" -> "Cache resolved domains to reduce repeated queries"
    "指定使用系统 DNS 的应用" -> "Specify apps that use the system DNS"
    "选择配置内容并导入或导出" -> "Choose configuration content to import or export"
    "选择应用界面语言" -> "Choose the app interface language"
    "自定义间隔" -> "Custom interval"
    "谛听" -> "DNSSR"
    "已开启" -> "On"
    "已关闭" -> "Off"
    "谛听 服务" -> "DNSSR service"
    "谛听 监控" -> "DNSSR monitor"
    "地址" -> "Address"
    "端口" -> "Port"
    "账号（可选）" -> "Username (optional)"
    "密码（可选）" -> "Password (optional)"
    "模板名称" -> "Template name"
    "模板地址" -> "Template URL"
    "复制域名" -> "Copy domain"
    "检查失败，点击重试" -> "Check failed. Tap to retry"
    "可下载" -> "Available to download"
    "安装包已下载，点击安装" -> "Package downloaded. Tap to install"
    "上次下载失败，点击重试" -> "Previous download failed. Tap to retry"
    "下载中" -> "Downloading"
    "安装" -> "Install"
    "重新下载" -> "Download again"
    "应用启动时不自动检查，可随时手动检查" -> "Do not check automatically at startup; check manually at any time"
    "稍后" -> "Later"
    "暂无样本" -> "No samples"
    "冷却中" -> "Cooling down"
    "配置" -> "Configuration"
    "配置已导出" -> "Configuration exported"
    "无法打开导出文件" -> "Unable to open export file"
    "正在准备导出" -> "Preparing export"
    "正在写入文件" -> "Writing file"
    "正在读取配置文件" -> "Reading configuration file"
    "正在生成 HTTPS 备份" -> "Generating HTTPS backup"
    "正在生成导出文件" -> "Generating export file"
    "无法读取配置文件" -> "Unable to read configuration file"
    "配置中包含不支持的 DNS 协议" -> "The configuration contains an unsupported DNS protocol"
    "配置列表格式错误" -> "The configuration list has an invalid format"
    "恢复完成：" -> "Restore complete:"
    "应用信息" -> "App information"
    "加密上游" -> "Encrypted upstreams"
    "配置流转" -> "Configuration transfer"
    "快捷控制" -> "Quick controls"
    "应用管控" -> "App controls"
    "提供系统快捷设置磁贴，方便快速启停 DNS 本地通道。" -> "Provides a system Quick Settings tile for rapidly starting and stopping the local DNS channel."
    "按应用排除 VPN 或阻止联网，灵活控制每个应用的网络访问。" -> "Exclude apps from the VPN or block their network access for per-app control."
    "默认仅处理 DNS" -> "DNS only by default"
    "实际解析表现" -> "Resolution behavior"
    "隐私与本地存储" -> "Privacy and local storage"
    "无法打开链接" -> "Unable to open link"
    "已保存检查应用" -> "Inspection apps saved"
    "关闭后不会删除已有日志，重新开启即可继续查看。" -> "Disabling this does not delete existing logs; enable it again to continue viewing them."
    "暂无模板。点击上方“添加模板”开始使用。" -> "No templates. Tap Add template above to get started."
    "添加模板" -> "Add template"
    "失败后回退直连" -> "Fall back to direct connection after failure"
    "旁路" -> "Bypassed"
    "正在导入中" -> "Import already in progress"
    "导入失败" -> "Import failed"
    "已创建分组" -> "Group created"
    "分组名称不能为空" -> "Group name cannot be empty"
    "分组名称已存在" -> "Group name already exists"
    "操作失败" -> "Operation failed"
    "目标域名" -> "Target domain"
    "模板必须使用 HTTP 或 HTTPS" -> "Template must use HTTP or HTTPS"
    "模板缺少 URL 占位符" -> "Template is missing a URL placeholder"
    "导入成功" -> "Import successful"
    "导入完成" -> "Import complete"
    "无法读取所选文件" -> "Unable to read the selected file"
    "安装包不存在或无法打开，请重新下载。" -> "The package does not exist or cannot be opened. Download it again."
    "下载完成，请点击安装。" -> "Download complete. Tap Install."
    "传统 DNS 过滤" -> "Traditional DNS filtering"
    "服务显示" -> "Provider visibility"
    "请先添加一张图片" -> "Add an image first"
    "继续开启" -> "Keep enabled"
    "不开启" -> "Do not enable"
    "当前背景" -> "Current background"
    "启动按钮" -> "Start button"
    "模式切换按钮" -> "Mode switch button"
    "首页古诗" -> "Home poem"
    "DNS 服务详情" -> "DNS service details"
    "无" -> "None"
    "操作" -> "Actions"
    "编辑模板" -> "Edit template"
    "删除模板" -> "Delete template"
    "必须使用 HTTP(S) 并包含至少一个占位符" -> "Must use HTTP(S) and contain at least one placeholder"
    "保存中..." -> "Saving..."
    "添加中..." -> "Adding..."
    "策略概览" -> "Strategy overview"
    "暂无胜出记录" -> "No wins recorded"
    "全部已记录请求" -> "All recorded requests"
    "已删除" -> "Deleted"
    "已启用" -> "Enabled"
    "已禁用" -> "Disabled"
    "中文" -> "Chinese"
    "关闭" -> "Off"
    "代理可用" -> "Proxy available"
    "代理不可用" -> "Proxy unavailable"
    "未运行" -> "Not running"
    "已保存" -> "Saved"
    "日志已导出" -> "Logs exported"
    "导出失败" -> "Export failed"
    "以下操作会立即删除本机数据，删除后无法恢复。" -> "The following actions immediately delete local data and cannot be undone."
    "查看全部" -> "View all"
    "详情" -> "Details"
    "隐私模式运行中" -> "Privacy mode is running"
    "下一步" -> "Next"
    "上一步" -> "Previous"
    "重命名分组" -> "Rename group"
    "分组名称" -> "Group name"
    "新建分组名称（可选）" -> "New group name (optional)"
    "未分组" -> "Ungrouped"
    "未使用" -> "Not used"
    "未选择模板" -> "No template selected"
    "例如：EasyList China" -> "Example: EasyList China"
    "感谢每一位支持项目的朋友！" -> "Thanks to everyone who supports the project!"
    "代理账号或密码过长" -> "The proxy username or password is too long"
    "其他设置" -> "Other settings"
    "设置自定义 DNS 服务的名称" -> "Set the name of a custom DNS service"
    "管理内置解析 IP" -> "Manage built-in resolution IPs"
    "添加和管理自定义解析 IP" -> "Add and manage custom resolution IPs"
    "启用或关闭本地响应缓存" -> "Enable or disable the local response cache"
    "最长 1 小时，短 TTL 至少 1 分钟" -> "Up to 1 hour; short TTLs are at least 1 minute"
    "最长 6 小时，短 TTL 至少 2 分钟" -> "Up to 6 hours; short TTLs are at least 2 minutes"
    "设置日志记录范围" -> "Set the logging scope"
    "设置日志保留天数" -> "Set the log retention period"
    "后台显示悬浮球并查看最近请求" -> "Show a floating button in the background and view recent requests"
    "隐藏最近任务卡片" -> "Hide the recent-task card"
    "VPN 未运行时在通知栏常驻提醒" -> "Keep a notification reminder while the VPN is not running"
    "导入或导出名称、协议和解析地址" -> "Import or export names, protocols, and resolution addresses"
    "导入或导出名称、IP 和启用状态" -> "Import or export names, IPs, and enabled states"
    "导入或导出使用系统 DNS 的应用包名" -> "Import or export package names of apps using system DNS"
    "合并配置并跳过本机已有项目" -> "Merge configuration and skip items already on this device"
    "移除已缓存的解析结果" -> "Remove cached resolution results"
    "让所有首次进入说明再次显示" -> "Show all first-visit guides again"
    // 规则与订阅操作反馈
    "已添加到屏蔽规则" -> "Added to block rules"
    "已添加到白名单规则" -> "Added to allowlist rules"
    "已添加覆写域名" -> "Override domain added"
    "已添加 URL 规则" -> "URL rule added"
    "已删除全部地址规则" -> "All address rules deleted"
    "已删除全部域名规则" -> "All domain rules deleted"
    "已重命名规则订阅" -> "Rule subscription renamed"
    "规则添加成功" -> "Rule added successfully"
    "规则格式无效或已存在" -> "Invalid rule format or rule already exists"
    "请输入域名或通配符规则" -> "Enter a domain or wildcard rule"
    "文件中没有可导入的有效规则" -> "No valid rules to import in the file"
    "订阅中没有可导入的有效规则" -> "No valid rules to import in the subscription"
    "首次导入因应用意外终止而中断，残留规则已清理，请重新导入" -> "Initial import was interrupted because the app terminated unexpectedly; leftover rules were cleaned up. Please import again"
    "更新因应用意外终止而中断，已保留原有规则，请重新更新" -> "Update was interrupted because the app terminated unexpectedly; original rules were kept. Please update again"
    "地址规则备份不是有效的 JSON" -> "Address rule backup is not valid JSON"
    "不是地址规则备份文件" -> "Not an address rule backup file"
    "不支持的地址规则备份版本" -> "Unsupported address rule backup version"
    // 名单与头像
    "头像响应为空" -> "Empty avatar response"
    "头像文件过大" -> "Avatar file is too large"
    "头像文件无效" -> "Invalid avatar file"
    "头像文件名无效" -> "Invalid avatar file name"
    "名单响应为空" -> "Empty member list response"
    "名单配置过大" -> "Member list configuration is too large"
    "名单配置缺少版本" -> "Member list configuration is missing a version"
    "名单存在重复成员" -> "Member list contains duplicate members"
    "名单存在重复头像" -> "Member list contains duplicate avatars"
    "成员名称不能为空" -> "Member name cannot be empty"
    "感谢您对谛听项目的赞助支持" -> "Thank you for sponsoring the DNSSR project"
    // 旁路与日志
    "旁路原因 · 客户端 TLS 验证或握手未解密" -> "Bypass reason · Client TLS validation or handshake not decrypted"
    "旁路原因 · 上游服务器 TLS 握手异常" -> "Bypass reason · Upstream server TLS handshake error"
    "旁路原因 · 安全白名单 / 证书固定自动旁路" -> "Bypass reason · Auto bypass by security allowlist / certificate pinning"
    "旁路原因 · 未解密直接转发" -> "Bypass reason · Forwarded without decryption"
    "客户端 TLS 验证或握手未解密" -> "Client TLS validation or handshake not decrypted"
    "上游服务器 TLS 握手异常" -> "Upstream server TLS handshake error"
    "安全白名单 / 证书固定自动旁路" -> "Auto bypass by security allowlist / certificate pinning"
    "未解密直接转发" -> "Forwarded without decryption"
    "未知服务商" -> "Unknown provider"
    "未知 Bootstrap IP" -> "Unknown Bootstrap IP"
    "当前筛选下暂无请求记录" -> "No requests under the current filter"
    "已连接: " -> "Connected: "
    // 配置迁移与导入明细
    "正在读取配置文件..." -> "Reading configuration file..."
    "成功解析配置文件（版本 V8）" -> "Configuration file parsed (version V8)"
    "首页服务商卡片可见性设置" -> "Home provider card visibility settings"
    "应用白名单开关 -> 已启用" -> "App allowlist switch -> Enabled"
    "单应用域名放行开关 -> 已启用" -> "Per-app domain allowlist switch -> Enabled"
    "已同步更新运行时规则索引" -> "Runtime rule indexes synced"
    "=== 谛听应用配置导入明细 ===" -> "=== App configuration import details ==="
    "\n【新增项目】:" -> "\n[Added]:"
    "\n【跳过项目】:" -> "\n[Skipped]:"
    "\n【更新全局设置】:" -> "\n[Global settings updated]:"
    "\n=== 执行日志 ===" -> "\n=== Execution log ==="
    // 更新与错误
    "未知错误" -> "Unknown error"
    "响应内容为空" -> "Empty response body"
    "无法保存安装包" -> "Unable to save the installation package"
    // 应用信息与协议
    "赞助者名单" -> "Sponsor list"
    "默认通过 Android VpnService 建立仅处理 DNS 的本地通道；启用 HTTPS 流量检查或禁止联网后，Go 隧道使用 Go 用户态网络栈接管 TCP、UDP、DNS 和 HTTP(S) 流量。" -> "By default, an Android VpnService establishes a local tunnel that handles DNS only. When HTTPS traffic inspection or network blocking is enabled, the Go tunnel uses a Go userspace network stack to take over TCP, UDP, DNS, and HTTP(S) traffic."
    "通知用于显示 DNS VPN 的运行和停止状态。拒绝不会阻止核心功能运行，但你可能无法及时看到连接状态提醒。" -> "Notifications show the running and stopped states of the DNS VPN. Denying does not stop core features, but you may miss connection status alerts."
    "谛听需要建立本地 VPN 来处理和过滤 DNS 请求。此权限用于在设备上接管 DNS 流量，不会将全部网络流量发送到远程 VPN 服务器。" -> "DNSSR needs a local VPN to process and filter DNS requests. This permission takes over DNS traffic on the device; it does not send all network traffic to a remote VPN server."
    "交流群：1090225658 （入群答案：造梦）" -> "QQ group: 1090225658 (join answer: 造梦)"
    "下载" -> "Download"
    "清空" -> "Clear"
    "完成" -> "Done"
    "清空域名" -> "Clear domains"
    "未限制（全部放行）" -> "Unrestricted (all allowed)"
    "如 example.com" -> "e.g. example.com"
    "1.1.1.1 或 example.com" -> "1.1.1.1 or example.com"
    "暂无域名，当前处于全部放行状态。" -> "No domains yet; all connections are currently allowed."
    "此操作将清空所有已配置的应用专属白名单域名规则，清空后各应用将恢复全部放行状态。" -> "This will clear all configured per-app allowlist domain rules; all apps will return to the fully allowed state."
    "搜索应用或包名..." -> "Search apps or package names..."
    "添加该应用允许访问的白名单域名。保存后，该应用仅能连接白名单域名解析出的 IP，其余连接将被阻止。" -> "Add domains this app is allowed to access. Once saved, the app can only connect to IPs resolved from allowlist domains; other connections will be blocked."
    "未找到匹配应用" -> "No matching apps"
    "暂无符合条件的应用" -> "No apps match the criteria"
    "已保存，DNS VPN 正在重连" -> "Saved; DNS VPN is reconnecting"
    "已保存，下次启动 DNS VPN 时生效" -> "Saved; takes effect the next time the DNS VPN starts"
    // 杂项反馈
    // 规则标签与开关状态
    "反选排除此应用 (~\$app)" -> "Inverse match to exclude this app (~\$app)"
    else -> null
}

internal fun translateCommonPattern(text: String): String? = null
