package com.haoze.dnssr.ui.localization

/**
 * DNS/HTTPS 请求日志、悬浮窗日志、日志仪表盘、DNS 缓存记录及竞速统计本地化词条。
 */
internal fun translateLogsAndStatsExact(text: String): String? = when (text) {
    "应用流量统计" -> "App Traffic Stats"
    "按总流量" -> "By Total Traffic"
    "按下载流量" -> "By Download"
    "按上传流量" -> "By Upload"
    "按实时网速" -> "By Realtime Speed"
    "本次会话" -> "Current Session"
    "代理总流量" -> "Total Proxy Traffic"
    "此操作将清空所有已持久化的应用历史流量统计，清除后无法恢复。" -> "This will permanently delete all persisted app traffic history statistics."
    "为什么系统设置将全部流量算给谛听？" -> "Why does the system attribute all traffic to DNSSR?"
    "为什么系统流量全算给谛听？" -> "Why is system traffic attributed to DNSSR?"
    "因 Android VPN 机制，系统将代理出站归属于守护进程。谛听自身不偷跑流量，点击查看原理解析。" -> "Due to the Android VPN architecture, outbound proxy traffic is counted under the daemon process. DNSSR itself does not consume traffic; tap to learn how it works."
    "今日消耗" -> "Today"
    "历史累计" -> "All-time History"
    "历史日消耗记录" -> "Daily History"
    "应用流量监控" -> "App Traffic Monitor"
    "今日代理流量" -> "Today's Proxy Traffic"
    "有效缓存" -> "Valid cache entries"
    "请求日志" -> "Request logs"
    "请求未被读取或过滤，直接建立连接" -> "The request was not read or filtered; the connection was established directly"
    "记录全部请求" -> "Recording all requests"
    "请求日志已关闭" -> "Request logging is off"
    "今日流量结构" -> "Today's traffic breakdown"
    "DNS 请求日志" -> "DNS request logs"
    "悬浮窗" -> "Floating window"
    "悬浮窗日志" -> "Floating-window logs"
    "需要系统悬浮窗权限；回到应用前台时悬浮窗会自动隐藏。" -> "System floating-window permission is required; the window hides automatically when the app returns to the foreground."
    "不创建或写入 DNS 请求日志" -> "Do not create or write DNS request logs"
    "DNS 与 HTTPS 日志合计，含通过、屏蔽和失败" -> "Combined DNS and HTTPS logs, including passed, blocked, and failed requests"
    "请求记录" -> "Request records"
    "缓存记录" -> "Cache records"
    "选择需要检查 HTTP(S) 流量的应用" -> "Choose apps whose HTTP(S) traffic should be inspected"
    "尚未选择应用；开启后不会阻断流量" -> "No apps selected; traffic will not be blocked when enabled"
    "关闭后名单会保留，但不会阻断流量或启用 Go 隧道。" -> "After disabling, the list is retained but traffic is not blocked and the Go tunnel is not enabled."
    "暂无请求日志" -> "No request logs"
    "暂无有效缓存" -> "No valid cache entries"
    "DNS 缓存" -> "DNS cache"
    "本地 DNS 缓存" -> "Local DNS cache"
    "删除请求日志" -> "Delete request logs"
    "删除 DNS 缓存" -> "Delete DNS cache"
    "搜索缓存域名..." -> "Search cached domains..."
    "悬浮窗日志启动失败" -> "Failed to start floating log window"
    "最小化悬浮窗日志" -> "Minimize floating log window"
    "关闭悬浮窗日志" -> "Close floating log window"
    "协议不支持 · 直连" -> "Unsupported protocol · Direct"
    "资源保护 · 直连" -> "Resource protection · Direct"
    "HTTPS 请求记录" -> "HTTPS request records"
    "请求记录说明" -> "Request record details"
    "暂无请求记录" -> "No request records"
    "开启后首页日志按钮显示当前的日志分组页；关闭后显示新版日志仪表盘" -> "Show the current log groups from the home Logs button; when disabled, show the new log dashboard"
    "选择 DNS 请求日志的记录范围" -> "Choose what DNS request logs record"
    "当前筛选下暂无请求日志" -> "No request logs for the current filter"
    "未授予悬浮窗权限，悬浮窗日志未开启" -> "Overlay permission was not granted; floating logs are disabled"
    "无法打开悬浮窗权限设置" -> "Unable to open overlay permission settings"
    "请求日志仪表盘" -> "Request log dashboard"
    "竞速统计" -> "Race statistics"
    "记录全部" -> "Record all"
    "仅拦截和错误" -> "Blocked and errors only"
    "暂无 DNS 缓存" -> "No DNS cache entries"
    "日志仪表盘" -> "Log dashboard"
    "重新开启日志后，仪表盘将从新产生的请求开始统计。" -> "After logging is enabled again, the dashboard will count new requests."
    "清除 DNS 和 HTTP 的历史请求记录" -> "Clear historical DNS and HTTP request records"
    "服务状态与解析概览" -> "Service status and resolution overview"
    "当前处于隐私模式，不记录请求明细。DNS 缓存、并发竞速与网络流量监控仍正常运行。" -> "Privacy mode is active; request details are not recorded. DNS cache, race resolution, and network traffic monitor remain fully operational."
    "隐私模式保护中" -> "Privacy mode active"
    "日志已关闭" -> "Logging disabled"
    "重新开启日志后，仪表盘将从新产生的请求开始统计。当前各类解析服务与缓存热点均正常工作。" -> "After logging is re-enabled, the dashboard will count new requests. Resolution services and cache hotspots continue to operate normally."
    "累计缓存命中" -> "Total cache hits"
    "并发竞速请求" -> "Race requests"
    "解析效能概况" -> "Resolution performance"
    "实时统计" -> "Live stats"
    // 重点请求仪表盘
    "重点请求仪表盘" -> "Priority request dashboard"
    "DNS 与 HTTPS 拦截、错误、旁路记录及解析状态概览" -> "Overview of DNS and HTTPS blocks, errors, bypass records, and resolution status"
    "重点记录" -> "Priority records"
    "过滤拦截" -> "Blocked"
    "异常失败" -> "Errors"
    "旁路直连" -> "Bypassed"
    "重点流量结构" -> "Priority traffic breakdown"
    "拦截占比" -> "Block share"
    "最近拦截与错误" -> "Recent blocks and errors"
    "清除历史" -> "Clear history"
    "暂无流量数据" -> "No traffic data yet"
    // 请求状态解释与时间范围
    "显示所有请求记录" -> "Show all request records"
    "近 7 天" -> "Last 7 days"
    "7 天" -> "7 days"
    // 流量归属说明弹窗
    "💡 真实流量关系等式" -> "💡 True traffic accounting equation"
    "系统统计 谛听 (50 GB) = 哔哩哔哩 (30 GB) + 抖音 (15 GB) + 微信 (5 GB)" -> "System stats: DNSSR (50 GB) = Bilibili (30 GB) + Douyin (15 GB) + WeChat (5 GB)"
    "1. Linux 内核归属机制" -> "1. Linux kernel attribution"
    "Android 底层网络栈严格按照「创建物理连接的进程 UID」统计流量。当开启 VPN 代理时，各应用的原始网络数据被路由给谛听，谛听通过自身的受保护套接字与外部网络传输。因此在系统设置眼里，所有外网流量都是由谛听创建的 Socket 产生的。" -> "The Android network stack attributes traffic strictly to the UID that created the physical connection. When VPN proxying is enabled, each app's raw traffic is routed to DNSSR, which forwards it through its own protected sockets. In the eyes of system settings, all outbound traffic comes from sockets created by DNSSR."
    "2. 为什么第三方软件无法修改系统设置" -> "2. Why third-party apps cannot change system statistics"
    "修改系统全局流量账本需要系统级签名权限（android.permission.UPDATE_DEVICE_STATS）。任何遵循 Google 安全规范的标准 VPN 应用都无权擅自篡改系统设置里的流量报表。" -> "Modifying the system-wide traffic ledger requires a system signature permission (android.permission.UPDATE_DEVICE_STATS). No standard VPN app that follows Google's security rules is allowed to alter the traffic report in system settings."
    "3. 谛听的透明性与隐私承诺" -> "3. DNSSR's transparency and privacy promise"
    "谛听本身绝不主动消耗外网业务流量。本页面展示的各应用实时网速和历史消耗，即为您设备上各个真实应用通过谛听中转时的精确流量分解，让您清清楚楚掌控每一字节流向。" -> "DNSSR never consumes external business traffic on its own. The realtime speeds and historical usage shown here are the precise traffic breakdown of your real apps relayed through DNSSR, so you can see exactly where every byte goes."
    else -> null
}

internal fun translateLogsAndStatsPattern(text: String): String? = when {
    text.contains(" · 命中缓存") -> text.replace(" · 命中缓存", " · Cache hit")
    text.startsWith("请求日志已关闭 · ") -> text.replace("请求日志已关闭 · ", "Request logging is off · ")
    text.startsWith("调整悬浮窗大小，当前") -> text.replace("调整悬浮窗大小，当前", "Resize floating log window; current size: ")
    text.startsWith("悬浮窗：") -> text.replace("悬浮窗：", "Floating window: ")
    text.startsWith("当前筛选下暂无请求记录") -> "No request records for the current filter"
    text.contains("命中缓存") -> text.replace("命中缓存", "Cache hit")
    text.startsWith("需要系统悬浮窗权限") -> "System overlay permission is required. The floating window hides automatically when the app returns to the foreground."
    text.startsWith("超过所选时间的 DNS 请求日志") -> "DNS request logs older than the selected period are deleted automatically to control local storage usage."
    else -> null
}
