package com.haoze.dnssr.ui.localization

/**
 * DNS/HTTPS 规则、hosts 覆写、URL 规则、规则订阅、镜像模板及配置备份导入导出本地化词条。
 */
internal fun translateRulesAndSubscriptionExact(text: String): String? = when (text) {
    "启用域名规则" -> "Enable domain rules"
    "开启域名屏蔽、白名单及 IPv4/IPv6 覆写功能" -> "Enable domain blocking, allowlist, and IPv4/IPv6 rewrites"
    "开启 DNS 阶段域名屏蔽、白名单放行及 IPv4/IPv6 覆写" -> "Enable DNS-stage domain blocking, allowlist, and IPv4/IPv6 rewrites"
    "已禁用所有域名规则功能，查询将直接放行" -> "All domain rule features are disabled; queries will be passed directly"
    "已禁用 DNS 域名过滤，查询将直接放行" -> "DNS domain filtering is disabled; queries will be passed directly"
    "统一管理域名过滤、URL 规则及规则覆写的总控开关、拦截策略与在线规则订阅。黑名单、白名单与覆写名单可在功能中心中独立管理。" -> "Centrally manage master switches, blocking policies, and subscriptions for domain filtering, URL rules, and rewrites. Blacklist, whitelist, and rewrite list can be managed independently in Feature Hub."
    "已禁用 · 统一管理域名屏蔽、放行及 IPv4/IPv6 覆写" -> "Disabled · Manage domain block, allowlist, and IPv4/IPv6 rewrites"
    "统一管理 IPv4/IPv6 覆写及订阅规则，DNS 与 HTTPS 检查共用" -> "Manage IPv4/IPv6 override and subscription rules shared by DNS and HTTPS inspection"
    "已禁用 · 统一管理 IPv4/IPv6 覆写及订阅规则" -> "Disabled · Manage IPv4/IPv6 override and subscription rules"
    "URL 规则与内容过滤" -> "URL rules and content filtering"
    "运行中 · 解密流量匹配 URL 屏蔽、放行及重定向" -> "Running · Decrypted traffic matches URL block, allow, and rewrites"
    "未就绪 · 需先安装并验证 CA 根证书" -> "Not ready · Install and verify CA root certificate first"
    "未就绪 · 需在 HTTPS 流量检查中开启" -> "Not ready · Enable in HTTPS traffic inspection"
    "未就绪 · 需在 HTTPS 流量检查中选择目标应用" -> "Not ready · Select target apps in HTTPS traffic inspection"
    "未就绪 · 需在 HTTPS 流量检查中开启检查" -> "Not ready · Enable inspection in HTTPS traffic inspection"
    "已暂停 · 未启用解密 URL 过滤与重定向" -> "Paused · Decrypted URL filtering and rewrites disabled"
    "已暂停 · 未启用 URL 规则与重定向" -> "Paused · URL rules and rewrites disabled"
    "运行中" -> "Running"
    "未就绪" -> "Not ready"
    "URL 规则" -> "URL rules"
    "管理 HTTPS 检查的 URL 规则与重定向" -> "Manage URL rules and rewrites for HTTPS inspection"
    "未就绪 · 需在 HTTPS 流量检查中配置证书与目标应用" -> "Not ready · Configure certificate and target apps in HTTPS traffic inspection"
    "启用地址规则" -> "Enable address rules"
    "开启 URL 屏蔽、放行及 CNAME 覆写功能" -> "Enable URL blocking, allowlist, and CNAME rewrites"
    "已禁用所有地址规则功能，HTTP(S) 请求将直接放行" -> "All address rule features are disabled; HTTP(S) requests will be passed directly"
    "已开启（未就绪 · 需先安装并验证 CA 根证书）" -> "Enabled (Not ready · Install and verify CA root certificate first)"
    "已开启（未就绪 · 需在 HTTPS 流量检查中开启检查）" -> "Enabled (Not ready · Enable inspection in HTTPS traffic inspection)"
    "已开启（未就绪 · 需在 HTTPS 流量检查中选择目标应用）" -> "Enabled (Not ready · Select target apps in HTTPS traffic inspection)"
    "未就绪 · 需配置 CA 证书与 HTTPS 流量检查" -> "Not ready · Configure CA certificate and HTTPS traffic inspection"
    "已禁用 · 管理 HTTPS 解密后匹配的 URL 地址和路径前缀屏蔽、放行规则" -> "Disabled · Manage URL and path prefix block and allow rules after HTTPS decryption"
    "管理 HTTPS 解密后的 CNAME 覆写规则" -> "Manage CNAME override rules after HTTPS decryption"
    "已禁用 · 管理 HTTPS 解密后的 CNAME 覆写规则" -> "Disabled · Manage CNAME override rules after HTTPS decryption"
    "白名单规则" -> "Allowlist rules"
    "清除 DNS 的域名屏蔽、白名单和覆写规则" -> "Clear DNS domain block, allowlist, and override rules"
    "清除 Go 隧道的域名、URL、白名单和覆写规则" -> "Clear Go tunnel domain, URL, allowlist, and override rules"
    "导入规则..." -> "Importing rules..."
    "导入 DNS 过滤订阅文件" -> "Import DNS filtering subscription file"
    "导入 hosts 覆写订阅文件" -> "Import hosts override subscription file"
    "导入 HTTPS 过滤订阅文件" -> "Import HTTPS filtering subscription file"
    "导入 HTTPS 规则备份 JSON" -> "Import HTTPS rule backup JSON"
    "恢复为手动规则，不创建订阅" -> "Restore as manual rules without creating a subscription"
    "DNS 规则" -> "DNS rules"
    "HTTPS 规则" -> "HTTPS rules"
    "规则数据" -> "Rule data"
    "域名规则 TXT 用于 DNS 过滤和白名单；hosts TXT 用于 IP 覆写；地址 JSON 用于 URL 屏蔽和放行规则备份。" -> "Domain TXT is for DNS filtering and allow rules; hosts TXT is for IP rewrites; address JSON backs up URL blocking and allow rules."
    "导出当前生效域名规则" -> "Export active domain rules"
    "导出当前已启用的 DNS 过滤和白名单规则，可重新导入为本地订阅" -> "Export active DNS filtering and allow rules for re-import as a local subscription."
    "hosts 覆写规则 · TXT 文件" -> "Hosts rewrite rules · TXT file"
    "导出当前生效 hosts 覆写规则" -> "Export active hosts rewrite rules"
    "导出当前已启用的 IP 覆写规则，可通过 hosts 导入入口恢复" -> "Export active IP rewrite rules for restoration through the hosts import entry."
    "导出地址规则备份" -> "Export address rule backup"
    "备份手动添加的 URL 屏蔽和放行规则，可导入恢复" -> "Back up manually added URL blocking and allow rules for re-import."
    "导入 DNS 过滤和白名单 TXT" -> "Import DNS filtering and allow TXT"
    "外部 hosts 文件" -> "External hosts file"
    "导入 hosts 覆写 TXT" -> "Import hosts rewrite TXT"
    "导入地址规则 JSON 备份" -> "Import address rule JSON backup"
    "恢复手动添加的 URL 屏蔽和放行规则，不创建订阅" -> "Restore manually added URL blocking and allow rules without creating a subscription."
    "域名规则 · TXT 订阅文件" -> "Domain rules · TXT subscription file"
    "地址规则 · JSON 备份文件" -> "Address rules · JSON backup file"
    "选择规则类型后导出当前生效内容。域名规则导出为可订阅的 TXT，地址规则导出为可恢复的 JSON 备份。" -> "Choose a rule type to export currently active content. Domain rules are exported as subscribable TXT, while address rules are exported as a restorable JSON backup."
    "仅导出当前生效的规则。DNS 使用可订阅的 TXT，HTTPS 使用可完整恢复的备份 JSON。" -> "Only currently active rules are exported. DNS uses subscribable TXT, while HTTPS uses a fully restorable backup JSON."
    "请求正常放行，未命中拦截规则" -> "Request passed normally without matching a blocking rule"
    "请求命中了覆写规则，并返回覆写后的结果" -> "The request matched an override rule and returned the overridden result"
    "请求命中了过滤规则并被拦截" -> "The request matched a filtering rule and was blocked"
    "订阅拦截" -> "Subscription blocking"
    "暂无屏蔽订阅" -> "No blocking subscriptions"
    "动态策略开启时会临时覆盖以上选择：先返回 NODATA，高频请求后返回 NXDOMAIN。" -> "When dynamic policy is enabled, it temporarily overrides the selection above: return NODATA first, then NXDOMAIN for frequent requests."
    "正常客户端会缓存 NODATA 响应。动态策略主要用于持续重试或忽略负缓存的请求。" -> "Normal clients cache NODATA responses. Dynamic policy is mainly for repeated retries or requests that ignore negative caching."
    "NXDOMAIN 保持时长（秒）" -> "NXDOMAIN hold duration (seconds)"
    "规则拦截" -> "Rule blocking"
    "黑名单规则" -> "Blocklist rules"
    "删除本组全部订阅" -> "Delete all subscriptions in this group"
    "填写镜像站名称和地址格式" -> "Enter the mirror name and URL format"
    "请输入域名或支持的白名单规则" -> "Enter a domain or supported allowlist rule"
    "查看各订阅拦截请求的次数和占比" -> "View blocked request counts and ratios for each subscription"
    "返回域名不存在，并提供 5 分钟负缓存以减少重复查询" -> "Return NXDOMAIN with a five-minute negative cache to reduce repeated queries"
    "返回域名存在但没有该记录，并提供 5 分钟负缓存" -> "Return NODATA with a five-minute negative cache"
    "返回服务器拒绝该查询，不提供缓存记录" -> "Return REFUSED without a cacheable response"
    "域名不存在（NXDOMAIN）" -> "Domain does not exist (NXDOMAIN)"
    "域名存在但无记录（NODATA）" -> "Domain exists but has no record (NODATA)"
    "拒绝查询（REFUSED）" -> "Query refused (REFUSED)"
    "返回零地址" -> "Return zero address"
    "重命名订阅" -> "Rename subscription"
    "编辑订阅" -> "Edit subscription"
    "禁用规则" -> "Disable rules"
    "启用规则" -> "Enable rules"
    "删除规则" -> "Delete rules"
    "订阅信息" -> "Subscription information"
    "订阅分组" -> "Subscription group"
    "DNS 过滤规则" -> "DNS filtering rules"
    "网络 DNS 过滤订阅" -> "Network DNS filtering subscription"
    "hosts 覆写规则" -> "hosts override rules"
    "网络 hosts 覆写订阅" -> "Network hosts override subscription"
    "使用自定义镜像" -> "Use custom mirror"
    "选择镜像站模板" -> "Choose mirror template"
    "暂无模板，请先在域名规则 → 镜像站模板中添加。" -> "No templates. Add one under Domain rules -> Mirror templates first."
    "hosts 覆写" -> "hosts override"
    " · 自定义镜像" -> " · Custom mirror"
    "打开规则订阅操作" -> "Open rule subscription actions"
    "屏蔽规则" -> "Block rules"
    "放行规则" -> "Allow rules"
    "覆写域名规则" -> "Domain override rules"
    "覆写规则" -> "Override rules"
    "动态策略：先 NODATA，高频请求后 NXDOMAIN" -> "Dynamic policy: NODATA first, then NXDOMAIN for frequent requests"
    "URL 请求规则" -> "URL request rules"
    "添加放行 URL" -> "Add allowed URL"
    "如 https://example.com/allowed，可覆盖域名屏蔽" -> "For example, https://example.com/allowed; can override domain blocking"
    "URL 屏蔽规则" -> "URL block rules"
    "查看、启用、停用或删除 URL 屏蔽规则" -> "View, enable, disable, or delete URL block rules"
    "URL 放行规则" -> "URL allow rules"
    "查看、启用、停用或删除 URL 放行规则" -> "View, enable, disable, or delete URL allow rules"
    "域名屏蔽与放行" -> "Domain blocking and allowing"
    "添加放行域名" -> "Add allowed domain"
    "查看、启用、停用或删除屏蔽规则" -> "View, enable, disable, or delete block rules"
    "查看、启用、停用或删除放行规则" -> "View, enable, disable, or delete allow rules"
    "域名覆写" -> "Domain overrides"
    "添加覆写域名" -> "Add domain override"
    "将域名覆写为 IPv4 或 IPv6" -> "Override the domain with an IPv4 or IPv6 address"
    "将域名覆写为 CNAME" -> "Override the domain with a CNAME"
    "IPv4/IPv6 覆写规则" -> "IPv4/IPv6 override rules"
    "CNAME 覆写规则" -> "CNAME override rules"
    "查看、启用、停用或删除当前范围的覆写规则" -> "View, enable, disable, or delete overrides in the current scope"
    "管理 DNS 域名规则与 IPv4/IPv6 覆写订阅" -> "Manage DNS domain-rule and IPv4/IPv6 override subscriptions"
    "管理 HTTPS 域名、URL 与 CNAME 覆写订阅" -> "Manage HTTPS domain, URL, and CNAME override subscriptions"
    "维护订阅下载镜像，可在添加订阅时直接选择" -> "Maintain subscription download mirrors and select them when adding subscriptions"
    "清理全部 DNS 规则" -> "Clear all DNS rules"
    "清理全部 HTTPS 规则" -> "Clear all HTTPS rules"
    "清除当前 DNS 规则后可重新导入，不影响 Go 隧道规则" -> "Clear current DNS rules for re-import; Go tunnel rules are not affected"
    "清除当前 HTTPS 规则后可重新导入，不影响传统 DNS 规则" -> "Clear current HTTPS rules for re-import; legacy DNS rules are not affected"
    "删除全部 HTTPS 规则" -> "Delete all HTTPS rules"
    "确定要删除全部 DNS 规则吗？手动添加和订阅导入的域名屏蔽、白名单及 IPv4/IPv6 覆写规则都会被移除。Go 隧道规则不受影响。" -> "Delete all DNS rules? Manually added and subscription-imported domain block, allowlist, and IPv4/IPv6 override rules will be removed. Go tunnel rules are not affected."
    "确定要删除全部 HTTPS 规则吗？手动添加和订阅导入的域名、URL、白名单和覆写规则都会被移除。传统 DNS 规则不受影响。" -> "Delete all HTTPS rules? Manually added and subscription-imported domain, URL, allowlist, and override rules will be removed. Legacy DNS rules are not affected."
    "配置文件仅包含所选的自定义配置，不包含日志、缓存和已下载的域名规则。" -> "The configuration file contains only selected custom settings, excluding logs, cache, and downloaded domain rules."
    "网络规则订阅" -> "Network rule subscriptions"
    "订阅名称和链接" -> "Subscription names and URLs"
    "将勾选内容保存为 JSON 配置文件" -> "Save selected items as a JSON configuration file"
    "合并配置并跳过本机已有项目；网络订阅不会立即下载" -> "Merge the configuration and skip items already on this device; network subscriptions are not downloaded immediately"
    "DNS 解析、域名规则和其他基础功能不会受到影响。" -> "DNS resolution, domain rules, and other core features are not affected."
    "暂无规则拦截数据" -> "No rule blocking data"
    "暂无订阅拦截数据" -> "No subscription blocking data"
    "加入白名单规则" -> "Add to allowlist rules"
    "加入屏蔽规则" -> "Add to blocklist rules"
    "删除全部 DNS 规则" -> "Delete all DNS rules"
    "删除全部 HTTPS 过滤规则" -> "Delete all HTTPS filtering rules"
    "规则导入" -> "Rule import"
    "订阅地址" -> "Subscription URL"
    "删除规则订阅" -> "Delete rule subscription"
    "删除分组订阅" -> "Delete group subscriptions"
    "添加屏蔽域名" -> "Add blocked domain"
    "添加屏蔽 URL" -> "Add blocked URL"
    "请输入域名或支持的过滤规则" -> "Enter a domain or supported filter rule"
    "URL 规则无效、已存在，或包含不支持的通配符/修饰符" -> "The URL rule is invalid, already exists, or contains unsupported wildcards/modifiers"
    "域名或通配符规则，如 example.com 或 *-analytics.google.com" -> "Domain or wildcard rule, e.g. example.com or *-analytics.google.com"
    "域名或通配符规则，如 example.com 或 *" -> "Domain or wildcard rule, e.g. example.com or *"
    "域名、目标格式无效、规则冲突或已存在" -> "The domain or target format is invalid, conflicts with another rule, or already exists"
    "筛选规则来源" -> "Filter rule source"
    "搜索 URL 规则" -> "Search URL rules"
    "搜索域名或规则" -> "Search domains or rules"
    "全部规则" -> "All rules"
    "本地规则" -> "Local rules"
    "已覆写" -> "Rewritten"
    "导入规则" -> "Import rules"
    "订阅名称" -> "Subscription name"
    "域名规则使用说明" -> "Domain rules guide"
    "系统会在后台按此频率检查网络规则订阅，实际执行时间可能受系统调度影响。" -> "The system checks rule subscriptions in the background at this interval. The actual execution time may be affected by system scheduling."
    "备份或恢复自定义服务与规则订阅" -> "Back up or restore custom services and rule subscriptions"
    "将当前生效规则导出为 TXT 文件" -> "Export active rules as a TXT file"
    "从本地文件导入 DNS、hosts 和 HTTPS 规则" -> "Import DNS, hosts, and HTTPS rules from a local file"
    "删除缓存、日志或域名规则" -> "Delete cache, logs, or domain rules"
    "删除镜像站模板" -> "Delete mirror template"
    "规则" -> "Rules"
    "将当前生效规则导出为可订阅的 TXT 文件" -> "Export active rules as a subscribable TXT file"
    "正在读取 HTTPS 规则" -> "Reading HTTPS rules"
    "正在读取白名单规则" -> "Reading allowlist rules"
    "正在读取拦截规则" -> "Reading block rules"
    "配置文件不是有效的 JSON" -> "The configuration file is not valid JSON"
    "配置中包含无效的订阅链接" -> "The configuration contains an invalid subscription URL"
    "规则格式无效或规则已存在" -> "The rule format is invalid or the rule already exists"
    "HTTPS 规则备份不是有效的 JSON" -> "The HTTPS rule backup is not valid JSON"
    "不是 HTTPS 规则备份文件" -> "This is not an HTTPS rule backup file"
    "备份包含不支持的规则来源" -> "The backup contains an unsupported rule source"
    "备份不属于 HTTPS 规则" -> "The backup does not belong to HTTPS rules"
    "备份缺少规则内容" -> "The backup is missing rule contents"
    "备份包含不支持的覆写规则" -> "The backup contains an unsupported override rule"
    "备份规则格式错误" -> "The backup rule has an invalid format"
    "配置中包含无效的 URL 规则" -> "The backup contains an invalid URL rule"
    "规则与缓存" -> "Rules and cache"
    "以缓存、屏蔽规则、白名单和订阅规则减少重复请求与干扰。" -> "Reduces repeated requests and interference with caching, block rules, allowlists, and subscription rules."
    "解析速度、稳定性和可用性取决于网络环境、所选上游和本机规则。" -> "Resolution speed, stability, and availability depend on the network, selected upstreams, and local rules."
    "在 Android 设备本机管理 DNS 查询路径，让解析策略、缓存、规则与上游连接处于可控状态。" -> "Manage the DNS path on the Android device and keep resolution policies, cache, rules, and upstream connections under control."
    "例如：GitHub 镜像" -> "Example: GitHub mirror"
    "覆写" -> "Rewritten"
    "规则订阅" -> "Rule subscriptions"
    "添加订阅失败" -> "Failed to add subscription"
    "切换订阅状态失败" -> "Failed to change subscription state"
    "订阅链接必须使用 HTTP 或 HTTPS" -> "Subscription URL must use HTTP or HTTPS"
    "该订阅链接已存在" -> "This subscription URL already exists"
    "订阅名称不能为空" -> "Subscription name cannot be empty"
    "该文件已作为订阅导入" -> "This file has already been imported as a subscription"
    "订阅不存在" -> "Subscription not found"
    "订阅不属于当前规则范围" -> "The subscription is outside the current rule scope"
    "本地文件订阅仅支持重命名" -> "Local file subscriptions only support renaming"
    "订阅响应为空" -> "Subscription response is empty"
    "订阅中没有可导入的有效 DNS 规则" -> "The subscription contains no valid importable DNS rules"
    "订阅中没有可导入的有效 hosts 规则" -> "The subscription contains no valid importable hosts rules"
    "原始订阅地址格式无效" -> "The original subscription URL is invalid"
    "镜像模板必须包含 {url}、{urlEncoded}、{scheme}、{host}、{path} 或 {pathAndQuery}" -> "The mirror template must contain {url}, {urlEncoded}, {scheme}, {host}, {path}, or {pathAndQuery}"
    "镜像模板生成的地址必须使用 HTTP 或 HTTPS" -> "The URL generated by the mirror template must use HTTP or HTTPS"
    "正在启用规则订阅..." -> "Enabling rule subscription..."
    "正在禁用规则订阅..." -> "Disabling rule subscription..."
    "已启用规则订阅" -> "Rule subscription enabled"
    "已禁用规则订阅" -> "Rule subscription disabled"
    "镜像站名称不能为空" -> "Mirror name cannot be empty"
    "未知的规则操作" -> "Unknown rule operation"
    "订阅已保存" -> "Subscription saved"
    "订阅已是最新" -> "Subscription is already up to date"
    "HTTPS 规则备份只能在 HTTPS 过滤中导入" -> "HTTPS rule backups can only be imported in HTTPS filtering"
    "缺少规则文件" -> "Rule file is missing"
    "文件中没有可导入的有效 DNS 规则" -> "The file contains no valid importable DNS rules"
    "文件中没有可导入的真实 IP hosts 规则" -> "The file contains no valid IP hosts rules"
    "依据 AdGuard DNS 语法自动分类黑白名单。支持 BOM、行尾注释、hosts 多域名和 IDN 域名。" -> "Classify block and allow rules automatically using AdGuard DNS syntax. BOM, end-of-line comments, multiple hosts domains, and IDN domains are supported."
    "全部 DNS、HTTPS、缓存、竞速与规则拦截的实时概览" -> "A real-time overview of DNS, HTTPS, cache, race, and rule blocking"
    "镜像站模板" -> "Mirror templates"
    "保存常用的订阅下载镜像。添加规则订阅时，可以直接选择这里的模板。" -> "Save commonly used subscription download mirrors. Choose these templates directly when adding rule subscriptions."
    "镜像站格式示例" -> "Mirror format example"
    "了解占位符如何组成镜像地址" -> "Learn how placeholders form a mirror URL"
    "编辑镜像站模板" -> "Edit mirror template"
    "添加镜像站模板" -> "Add mirror template"
    "保存后，可在添加规则订阅时直接选择。" -> "After saving, it can be selected directly when adding a rule subscription."
    "已添加镜像站模板" -> "Mirror template added"
    "域名规则" -> "Domain rules"
    "地址规则" -> "Address rules"
    "规则类型" -> "Rule types"
    "规则范围" -> "Rule scope"
    "DNS 域名规则" -> "DNS domain rules"
    "HTTPS 域名规则" -> "HTTPS domain rules"
    "用于普通 DNS 请求的屏蔽、放行及 IPv4/IPv6 覆写" -> "Block, allow, and IPv4/IPv6 override rules for ordinary DNS requests"
    "自定义屏蔽和放行域名规则" -> "Custom block and allow domain rules"
    "手动添加的域名屏蔽与放行规则" -> "Manually added domain block and allow rules"
    "自定义复写域名规则" -> "Custom rewrite domain rules"
    "手动添加的 IPv4 / IPv6 域名覆写规则" -> "Manually added IPv4/IPv6 domain rewrite rules"
    "自定义复写 CNAME 规则" -> "Custom rewrite CNAME rules"
    "手动添加的 CNAME 域名覆写规则" -> "Manually added CNAME domain rewrite rules"
    "自定义屏蔽和放行地址规则" -> "Custom block and allow address rules"
    "手动添加的 URL 路径屏蔽与放行规则" -> "Manually added URL path block and allow rules"
    "DNS 服务与解析策略" -> "DNS Services & Resolution Policy"
    "规则与订阅配置" -> "Rules & Subscription Policy"
    "应用控制与流量管理" -> "App Control & Traffic Management"
    "个性化与通用设置" -> "Personalization & General Settings"
    "DNS 缓存策略" -> "DNS Cache Policy"
    "DNS 缓存开关、预设与 TTL 控制" -> "DNS cache switch, presets, and TTL controls"
    "出站代理配置" -> "Outbound Proxy Configuration"
    "SOCKS5 / HTTP 代理与代理应用" -> "SOCKS5 / HTTP proxy and proxy routing apps"
    "订阅源链接、镜像加速与自动更新" -> "Subscription sources, mirror acceleration, and auto-update"
    "自定义屏蔽域名规则" -> "Custom domain block rules"
    "手动添加的域名屏蔽规则及状态" -> "Manually added domain block rules and states"
    "HTTPS 抓包检测配置" -> "HTTPS Inspection Configuration"
    "流量抓包开关与目标应用名单" -> "Traffic inspection switch and target apps"
    "外观与界面个性化" -> "Appearance & UI Customization"
    "主题风格、组件透明度与标语" -> "Theme styles, component opacities, and sentences"
    "系统与通用设置" -> "System & General Settings"
    "局域网绕行、日志模式、语言与通知" -> "LAN bypass, log modes, language, and notifications"
    "预置 Bootstrap IP 节点" -> "Preset Bootstrap IP Nodes"
    "已同步预置 Bootstrap 节点启用状态" -> "Preset Bootstrap node states synchronized"
    "DNS 缓存配置" -> "DNS Cache Configuration"
    "已应用 DNS 缓存策略" -> "DNS cache policy applied"
    "已应用出站代理配置" -> "Outbound proxy configuration applied"
    "HTTPS 抓包配置" -> "HTTPS Inspection Configuration"
    "已应用 HTTPS 抓包配置" -> "HTTPS inspection configuration applied"
    "外观与主题设置" -> "Appearance & Theme Settings"
    "已应用外观与主题个性化配置" -> "Appearance & theme configuration applied"
    "已应用系统与通用设置" -> "System and general settings applied"
    "备份与恢复应用配置及自定义规则。" -> "Backup and restore app configuration and custom rules."
    "备份与恢复应用配置及自定义规则" -> "Backup and restore app configuration and custom rules"
    "将自定义 DNS 服务商、分流名单与各类自定义规则等导出为 JSON" -> "Export custom DNS providers, routing lists, and custom rules as JSON"
    "从 JSON 备份文件合并恢复应用配置与自定义规则" -> "Merge and restore app configuration and custom rules from JSON backup"
    "导出的配置文件包含个人自定义设置，请妥善保管；导入时将合并配置并自动跳过已存在的条目。" -> "Exported configuration files contain personal custom settings, please keep them safe; importing will merge settings and automatically skip existing entries."
    "DNS 服务商" -> "DNS providers"
    "自定义规则" -> "Custom rules"
    "名单应用" -> "Managed apps"
    "规则导出" -> "Rule export"
    "订阅规则拦截率" -> "Subscription rule block rate"
    "拦截率为所选时间范围内，该订阅拦截请求数占全部已记录请求（DNS + HTTPS）的比例。" -> "The block rate is the share of all recorded requests (DNS + HTTPS) blocked by the subscription in the selected time range."
    "屏蔽订阅" -> "Blocking subscriptions"
    "导入屏蔽订阅并产生 DNS 或 HTTPS 请求后，此处将显示其拦截率。" -> "The block rate appears here after a blocking subscription is imported and generates DNS or HTTPS requests."
    "已删除当前范围的全部规则" -> "All rules in the current scope were deleted"
    "已添加规则" -> "Rule added"
    "规则格式无效" -> "Invalid rule format"
    "暂无规则订阅" -> "No rule subscriptions"
    "该分组暂无规则订阅" -> "This group has no rule subscriptions"
    "点击右上角 + 添加 AdGuard DNS 规则地址" -> "Tap + above to add an AdGuard DNS rule URL"
    "添加规则订阅" -> "Add rule subscription"
    "添加规则订阅 (1/3)" -> "Add rule subscription (1/3)"
    "添加规则订阅 (2/3)" -> "Add rule subscription (2/3)"
    "添加规则订阅 (3/3)" -> "Add rule subscription (3/3)"
    "添加网络规则订阅" -> "Add network rule subscription"
    "支持 AdGuard、hosts 及复合网络规则订阅链接" -> "Supports AdGuard, hosts, and composite network rule subscription URLs"
    "从 DNS 范围复制已有网络订阅" -> "Copy existing network subscriptions from DNS scope"
    "输入规则订阅链接（支持 AdGuard 过滤/白名单、hosts 覆写及复合规则），系统将自动识别并分类导入。" -> "Enter a rule subscription URL (supports AdGuard filtering/allowlist, hosts rewrites, and composite rules). Rules are automatically identified and imported."
    "为订阅指定所属分组，便于分类管理和批量操作；也可以在此新建分组或保持未分组。" -> "Assign a group to this subscription for categorization and batch operations, or create a new group / keep it ungrouped."
    "若订阅源访问较慢或受限，可启用镜像站加速下载规则；无需加速可直接导入。" -> "If the subscription source is slow or restricted, enable a mirror template to speed up downloads. Otherwise, import directly."
    "支持 AdGuard DNS 过滤、白名单、hosts IP 覆写及复合规则自动分类。支持 BOM、行尾注释、hosts 多域名和 IDN 域名。" -> "Supports automatic classification for AdGuard DNS filtering, allowlist, hosts IP rewrites, and composite rules. Supports BOM, end-of-line comments, multi-domain hosts, and IDN."
    "域名与 IP 规则文件" -> "Domain and IP rule files"
    "导入规则文件（TXT / hosts）" -> "Import rule file (TXT / hosts)"
    "支持 AdGuard DNS 过滤、白名单、hosts IP 覆写及复合规则，系统自动识别并分类导入为本地订阅" -> "Supports AdGuard DNS filtering, allowlist, hosts IP rewrites, and composite rules. Automatically identified and imported as local subscriptions."
    "地址规则备份" -> "Address rule backup"
    "导入规则文件" -> "Import rule file"
    "从本地文件导入域名与 hosts 规则，支持全格式智能识别与地址规则恢复" -> "Import domain and hosts rules from local files with universal auto-classification and address rule restoration"
    "输入 AdGuard DNS 规则订阅地址，导入时会自动区分黑名单和白名单规则。" -> "Enter an AdGuard DNS rule subscription URL. Blocklist and allowlist rules are separated automatically during import."
    "条规则" -> "rules"
    "复制 DNS 订阅导入" -> "Copy DNS subscription import"
    "复制 DNS 的网络过滤订阅到 HTTPS，之后两边可独立维护。" -> "Copy a DNS network-filtering subscription to HTTPS so they can be maintained independently."
    "暂无可导入的 DNS 网络过滤订阅" -> "No importable DNS network-filtering subscriptions"
    "编辑规则订阅" -> "Edit rule subscription"
    "订阅名称（可选）" -> "Subscription name (optional)"
    "自定义镜像" -> "Custom mirror"
    "重命名规则订阅" -> "Rename rule subscription"
    "导入或导出订阅名称和链接" -> "Import or export subscription names and URLs"
    "删除全部规则" -> "Delete all rules"
    "清除手动添加和订阅导入的所有域名规则" -> "Clear all manually added and subscription-imported domain rules"
    "删除全部域名规则" -> "Delete all domain rules"
    "删除全部地址规则" -> "Delete all address rules"
    "清除域名屏蔽、白名单、覆写规则及对应订阅" -> "Clear domain block, allowlist, override rules, and their subscriptions"
    "清除 URL 屏蔽和放行规则" -> "Clear URL block and allow rules"
    "确定要删除全部 DNS 规则吗？域名屏蔽、白名单和覆写规则都会被移除。" -> "Delete all DNS rules? Domain block, allowlist, and override rules will be removed."
    "确定要删除全部 HTTPS 过滤规则吗？域名、URL、白名单和覆写规则都会被移除。" -> "Delete all HTTPS filtering rules? Domain, URL, allowlist, and override rules will be removed."
    "应用配置备份" -> "Application config backup"
    "全选" -> "Select all"
    "全不选" -> "Deselect all"
    "DoH、DoT 服务商与解析配置" -> "DoH and DoT providers and query settings"
    "引导 DNS 节点与启用状态" -> "Bootstrap DNS nodes and status"
    "订阅源链接与名称" -> "Subscription URLs and names"
    "排除应用名单" -> "Excluded apps"
    "绕过过滤使用系统 DNS 的应用" -> "Apps bypassing filtering and using system DNS"
    "禁止联网名单" -> "Blocked apps"
    "服务运行时禁止联网的应用" -> "Apps blocked from networking while service is running"
    "应用白名单" -> "Per-app domain allowlist"
    "单应用域名放行" -> "Per-app domain allowlist"
    "白名单受限应用与域名规则" -> "Restricted apps and allowlist domain rules"
    "放行受限应用与域名规则" -> "Restricted apps and allowlist domain rules"
    "白名单" -> "Whitelist"
    "允许编辑默认白名单" -> "Allow editing default whitelist"
    "风险提示" -> "Risk warning"
    "放行统计与状态" -> "Allowlist statistics & status"
    "放行域名数" -> "Whitelisted domains"
    "默认预设" -> "Default preset"
    "用户自定义" -> "User custom"
    "放行 URL" -> "Allowed URLs"
    "重置默认白名单" -> "Reset default whitelist"
    "清空自定义白名单" -> "Clear custom whitelist"
    "添加白名单规则" -> "Add whitelist rule"
    "编辑白名单规则" -> "Edit whitelist rule"
    "编辑默认预设规则" -> "Edit default preset rule"
    "删除白名单规则" -> "Delete whitelist rule"
    "黑名单" -> "Blacklist"
    "拦截统计与状态" -> "Blocking statistics & status"
    "拦截域名数" -> "Blocked domains"
    "清空自定义黑名单" -> "Clear custom blocklist"
    "清空黑名单" -> "Clear blocklist"
    "添加黑名单规则" -> "Add blocklist rule"
    "编辑黑名单规则" -> "Edit blocklist rule"
    "删除黑名单规则" -> "Delete blocklist rule"
    "添加黑名单" -> "Add to blocklist"
    "已清空自定义黑名单" -> "Custom blocklist cleared"
    "已清空黑名单" -> "Blocklist cleared"
    "暂无黑名单规则" -> "No blocklist rules"
    "已添加域名黑名单规则" -> "Added domain blocklist rule"
    "已添加 URL 屏蔽规则" -> "Added URL block rule"
    "确定要清空所有由您添加的自定义黑名单规则吗？规则订阅等内容不受影响。" -> "Are you sure you want to clear all custom blocklist rules added by you? Rule subscriptions are not affected."
    "支持域名（如 example.com、*.google.com）、AdGuard 规则（||example.com^）或 URL 屏蔽前缀（https://example.com/api）。" -> "Supports domains (e.g. example.com, *.google.com), AdGuard rules (||example.com^), or URL block prefixes (https://example.com/api)."
    "导出应用配置 (JSON)" -> "Export application config (JSON)"
    "将勾选的自定义配置打包保存为 JSON 文件" -> "Package selected custom settings into a JSON file"
    "导入应用配置 (JSON)" -> "Import application config (JSON)"
    "从备份文件合并配置，自动跳过本机已存在项目" -> "Merge config from backup, automatically skipping existing items"
    "导出域名规则 (TXT)" -> "Export domain rules (TXT)"
    "导出当前已启用的 DNS 过滤与白名单规则" -> "Export currently active DNS filtering and allowlist rules"
    "导出 hosts 覆写 (TXT)" -> "Export hosts rewrite (TXT)"
    "导出当前已启用的 IP 覆写规则" -> "Export currently active IP rewrite rules"
    "导出地址规则备份 (JSON)" -> "Export address rule backup (JSON)"
    "导出手动添加的 URL 拦截与放行规则" -> "Export manually added URL block and allow rules"
    "导入规则文件 (TXT / hosts)" -> "Import rule file (TXT / hosts)"
    "识别本地规则文件并保存为本地订阅" -> "Detect local rule files and save as local subscriptions"
    "导入地址规则 (JSON)" -> "Import address rules (JSON)"
    "从备份文件恢复手动添加的 URL 规则" -> "Restore manually added URL rules from backup"
    "导出的配置文件包含个人自定义设置，请妥善保管；本地导入的规则将作为本地订阅保存在本机。" -> "Exported configuration contains personal custom settings; imported rules will be saved as local subscriptions."
    "数据流转与备份" -> "Data transfer and backup"
    "备份与恢复应用配置，或导入与导出本地规则文件。" -> "Back up and restore app configuration, or import and export local rule files."
    "本地订阅导入后无法自动在线更新。" -> "Local subscriptions cannot be automatically updated online."
    "正在导入配置" -> "Importing configuration"
    // CNAME/覆写与清理
    "覆写名单" -> "Rewrite List"
    "覆写统计与状态" -> "Rewrite statistics & status"
    "IPv4 覆写" -> "IPv4 rewrite"
    "IPv6 覆写" -> "IPv6 rewrite"
    "CNAME 覆写" -> "CNAME rewrite"
    "添加覆写规则" -> "Add rewrite rule"
    "编辑覆写规则" -> "Edit rewrite rule"
    "删除覆写规则" -> "Delete rewrite rule"
    "清空自定义覆写" -> "Clear custom rewrites"
    "已添加覆写规则" -> "Rewrite rule added"
    "已清空自定义覆写" -> "Custom rewrites cleared"
    "暂无覆写规则" -> "No rewrite rules"
    "将域名解析覆写为指定的 IPv4、IPv6 地址或 CNAME 目标域名。" -> "Rewrite domain resolution to the specified IPv4, IPv6 address, or CNAME target domain."
    "确定要清空所有由您添加的自定义覆写规则吗？规则订阅等内容不受影响。" -> "Are you sure you want to clear all custom rewrite rules added by you? Rule subscriptions are not affected."
    "目标域名 (CNAME)" -> "Target domain (CNAME)"
    "目标地址不能为空" -> "Target address cannot be empty"
    "域名、目标格式无效或存在规则冲突" -> "Invalid domain or target format, or rule conflict exists"
    "修改失败：格式无效或存在规则冲突" -> "Edit failed: invalid format or rule conflict exists"
    "搜索域名或目标地址..." -> "Search domain or target address..."
    "规则控制" -> "Rule Control"
    "订阅与更新" -> "Subscriptions & Updates"
    "过滤与覆写控制" -> "Filtering & Override Control"
    "统一管理域名过滤、地址过滤及规则覆写的总控开关与拦截响应策略。黑名单、白名单与覆写名单可在功能中心中独立管理。" -> "Centrally manage master switches for domain filtering, address filtering, and rule overrides, as well as block response policies. Blocklist, allowlist, and rewrite list can be independently managed in the Feature Hub."
    "统一管理在线规则订阅源、自动更新计划及镜像下载加速。" -> "Centrally manage online rule subscription sources, auto-update schedules, and mirror download acceleration."
    "开启 DNS 域名屏蔽、白名单放行及 IPv4/IPv6 覆写" -> "Enable DNS domain blocking, allowlist bypass, and IPv4/IPv6 overrides"
    "开启 HTTPS 流量解密下的 URL 屏蔽、放行及 CNAME 覆写" -> "Enable URL blocking, allowing, and CNAME overrides under HTTPS traffic inspection"
    "管理域名规则与 IPv4/IPv6 覆写订阅源及分组" -> "Manage domain rules and IPv4/IPv6 override subscription sources and groups"
    "已关闭自动更新" -> "Auto-update is disabled"
    "统一管理拦截策略及订阅规则，DNS 与 HTTPS 检查共用" -> "Unified management of intercept policies and subscription rules, shared between DNS and HTTPS inspection"
    "已禁用 · 统一管理拦截策略及订阅规则" -> "Disabled · Unified management of intercept policies and subscription rules"
    "管理 HTTPS 检查的地址规则总开关" -> "Manage master switch for HTTPS inspection address rules"
    "已禁用 · 管理 HTTPS 检查的地址规则总开关" -> "Disabled · Manage master switch for HTTPS inspection address rules"
    "统一管理拦截响应策略与规则订阅，DNS 与 HTTPS 检查共用。屏蔽、放行与覆写请前往功能中心「黑名单」、「白名单」与「覆写名单」。" -> "Unified management of intercept response policies and subscription rules, shared by DNS and HTTPS inspection. For blocking, allowing, and rewriting, go to Feature Hub “Blocklist”, “Allowlist”, and “Rewrite List”."
    "仅在 HTTPS 流量检查可解密的 HTTP(S) 请求中生效。屏蔽、放行与覆写请前往功能中心「黑名单」、「白名单」与「覆写名单」。" -> "Only effective for HTTP(S) requests decryptable by HTTPS inspection. For blocking, allowing, and rewriting, go to Feature Hub “Blocklist”, “Allowlist”, and “Rewrite List”."
    "域名规则已关闭，所有域名功能均被禁用。屏蔽、放行与覆写请前往功能中心「黑名单」、「白名单」与「覆写名单」。" -> "Domain rules are disabled, all domain features are inactive. For blocking, allowing, and rewriting, go to Feature Hub “Blocklist”, “Allowlist”, and “Rewrite List”."
    "地址规则已关闭，所有地址规则功能均被禁用。屏蔽、放行与覆写请前往功能中心「黑名单」、「白名单」与「覆写名单」。" -> "Address rules are disabled, all address rule features are inactive. For blocking, allowing, and rewriting, go to Feature Hub “Blocklist”, “Allowlist”, and “Rewrite List”."
    "添加 CNAME 覆写" -> "Add CNAME override"
    "将域名覆写为指定的 CNAME 域名" -> "Rewrite a domain to the specified CNAME domain"
    "查看、启用、停用或删除 CNAME 覆写规则" -> "View, enable, disable, or delete CNAME override rules"
    "管理域名规则与 IPv4/IPv6 覆写订阅" -> "Manage domain rules and IPv4/IPv6 override subscriptions"
    "清理全部域名规则" -> "Clear all domain rules"
    "清除全部域名屏蔽、放行、覆写规则及对应订阅，不影响地址规则" -> "Clear all domain block, allow, and override rules with their subscriptions; address rules are not affected"
    "清理全部地址规则" -> "Clear all address rules"
    "清除全部 URL 屏蔽和放行规则，不影响域名规则" -> "Clear all URL block and allow rules; domain rules are not affected"
    "清除全部 URL 屏蔽、放行和 CNAME 覆写规则，不影响域名规则" -> "Clear all URL block, allow, and CNAME override rules; domain rules are not affected"
    "完整 URL，如 https://example.com/js" -> "Full URL, e.g. https://example.com/js"
    "如 https://example.com/js，匹配该路径前缀" -> "e.g. https://example.com/js; matches this path prefix"
    "生效应用包名 (可选，留空为全部应用)" -> "Effective package names (optional; leave empty for all apps)"
    "确定要删除全部地址规则吗？URL 屏蔽和放行规则都会被移除，域名规则不受影响。" -> "Delete all address rules? URL block and allow rules will be removed; domain rules are not affected."
    "确定要删除全部地址规则吗？URL 屏蔽、放行和 CNAME 覆写规则都会被移除，域名规则不受影响。" -> "Delete all address rules? URL block, allow, and CNAME override rules will be removed; domain rules are not affected."
    "确定要删除全部域名规则吗？域名屏蔽、白名单、IPv4/IPv6 覆写规则及对应订阅都会被移除，地址规则不受影响。" -> "Delete all domain rules? Domain block, allow, IPv4/IPv6 override rules, and their subscriptions will be removed; address rules are not affected."
    "确定要删除所有本地 DNS 缓存吗？下次访问域名时会重新查询。" -> "Delete all local DNS cache? Domains will be re-queried on the next access."
    "确定要删除全部域名规则吗？域名屏蔽、白名单、覆写规则及对应订阅都会被移除。" -> "Delete all domain rules? Domain block, allow, and override rules with their subscriptions will be removed."
    "确定要删除全部地址规则吗？URL 屏蔽和放行规则都会被移除。" -> "Delete all address rules? URL block and allow rules will be removed."
    "恢复竞速模式默认权重" -> "Restore default race mode weights"
    "恢复 Bootstrap IP 默认权重" -> "Restore default Bootstrap IP weights"
    "已恢复 DNS 默认权重" -> "Default DNS weights restored"
    "已恢复 Bootstrap 权重" -> "Default Bootstrap weights restored"
    "订阅源链接、镜像加速与名称" -> "Subscription source link, mirror acceleration, and name"
    else -> null
}

internal fun translateRulesAndSubscriptionPattern(text: String): String? = when {
    text.contains(" / ") && text.startsWith("正在导入规则...") -> text.replace("正在导入规则...", "Importing rules...")
    text.startsWith("导出订阅规则") -> text.replace("导出订阅规则", "Export subscription rules")
    text.startsWith("导出手动添加规则") -> text.replace("导出手动添加规则", "Export manually added rules")
    text.startsWith("导出全部规则") -> text.replace("导出全部规则", "Export all rules")
    text.startsWith("导出 DNS ") -> text.replace("导出 DNS ", "Export DNS ").replace("订阅规则", "subscription rules").replace("手动添加规则", "manually added rules").replace("全部规则", "all rules")
    text.startsWith("导出 HTTPS ") -> text.replace("导出 HTTPS ", "Export HTTPS ").replace("订阅规则", "subscription rules").replace("手动添加规则", "manually added rules").replace("全部规则", "all rules")
    text.startsWith("导出所有订阅导入的当前生效规则") -> text.replace("导出所有订阅导入的当前生效规则", "Export all currently active subscription-imported rules").replace("，保存为TXT 订阅文件", ", saved as a TXT subscription file").replace("，保存为可恢复的 JSON 备份", ", saved as a restorable JSON backup")
    text.startsWith("导出所有手动添加的当前生效规则") -> text.replace("导出所有手动添加的当前生效规则", "Export all currently active manually added rules").replace("，保存为TXT 订阅文件", ", saved as a TXT subscription file").replace("，保存为可恢复的 JSON 备份", ", saved as a restorable JSON backup")
    text.startsWith("合并订阅导入与手动添加的当前生效规则") -> text.replace("合并订阅导入与手动添加的当前生效规则", "Combine currently active subscription-imported and manually added rules").replace("，保存为TXT 订阅文件", ", saved as a TXT subscription file").replace("，保存为可恢复的 JSON 备份", ", saved as a restorable JSON backup")
    text.contains("保存为TXT 订阅文件") -> text.replace("保存为TXT 订阅文件", "saved as a TXT subscription file")
    text.contains("保存为可恢复的 JSON 备份") -> text.replace("保存为可恢复的 JSON 备份", "saved as a restorable JSON backup")
    text.startsWith("匹配规则 · ") -> text.replace("匹配规则 · ", "Matched rule · ")
    text.startsWith("共 ") && text.contains(" 条") -> text
                .replace("共 ", "")
                .replace(" 条", " ")
                .replace("域名规则", "domain rules")
                .replace("白名单规则", "allowlist rules")
                .replace("屏蔽规则", "blocklist rules")
                .replace("覆写规则", "override rules")
    text.startsWith("DNS 解析、域名规则") -> "DNS resolution, domain rules, and other basic features are not affected."
    text.startsWith("动态策略开启时会临时覆盖") -> "When dynamic policy is enabled, it temporarily overrides the selection: it returns NODATA first, then NXDOMAIN for frequent requests."
    text.startsWith("正常客户端会缓存 NODATA") -> "Normal clients cache NODATA responses. Dynamic policy is mainly for repeated retries or requests that ignore negative caching."
    text.startsWith("DNS ") && text.contains("已导出：") -> text.replace("DNS ", "DNS ").replace("订阅规则已导出：", "subscription rules exported: ").replace("手动添加规则已导出：", "manually added rules exported: ").replace("全部规则已导出：", "all rules exported: ")
    text.startsWith("HTTPS ") && text.contains("已导出：") -> text.replace("HTTPS ", "HTTPS ").replace("订阅规则已导出：", "subscription rules exported: ").replace("手动添加规则已导出：", "manually added rules exported: ").replace("全部规则已导出：", "all rules exported: ")
    text.startsWith("屏蔽 ") && text.contains(" 条，放行 ") -> text.replace("屏蔽 ", "Blocked ").replace(" 条，放行 ", ", allowed ").replace(" 条，CNAME ", ", CNAME ").replace("，URL 屏蔽 ", ", URL blocked ").replace(" 条，URL 放行 ", ", URL allowed ").replace(" 条", " rules")
    text.startsWith("配置中包含不支持的订阅作用域：") -> text.replace("配置中包含不支持的订阅作用域：", "The configuration contains an unsupported subscription scope: ")
    text.startsWith("恢复完成：屏蔽 ") -> text.replace("恢复完成：屏蔽 ", "Restore complete: blocked ").replace(" 条，放行 ", ", allowed ").replace(" 条，CNAME ", ", CNAME ").replace(" 条，URL 屏蔽 ", ", URL blocked ").replace(" 条，URL 放行 ", ", URL allowed ").replace(" 条，跳过 ", ", skipped ").replace(" 条", " rules")
    text.startsWith("备份包含无效的") -> text.replace("备份包含无效的", "The backup contains an invalid ").replace("屏蔽规则", "block rule").replace("放行规则", "allow rule").replace("覆写规则", "override rule").replace("URL 规则", "URL rule")
    text.startsWith("已删除订阅 #") -> text.replace("已删除订阅 #", "Deleted subscription #")
    text.startsWith("确定要删除“") -> text.replace("确定要删除“", "Delete “").replace("”吗？已使用此模板的订阅不会被修改。", "”? Subscriptions already using this template will not be changed.")
    text.startsWith("镜像下载失败") -> text.replace("镜像下载失败", "Mirror download failed")
    text.startsWith("已重命名规则订阅") -> "Rule subscription renamed"
    text.startsWith("确定要删除自定义黑名单规则「") -> text.replace("确定要删除自定义黑名单规则「", "Are you sure you want to delete custom blocklist rule “").replace("」吗？", "”?")
    text.startsWith("确定要删除黑名单规则「") -> text.replace("确定要删除黑名单规则「", "Are you sure you want to delete blocklist rule “").replace("」吗？", "”?")
    text.startsWith("确定要删除自定义白名单规则「") -> text.replace("确定要删除自定义白名单规则「", "Are you sure you want to delete custom whitelist rule “").replace("」吗？", "”?")
    text.startsWith("确定要删除默认预设白名单规则「") -> text.replace("确定要删除默认预设白名单规则「", "Are you sure you want to delete default preset whitelist rule “").replace("」吗？若网络异常可通过右上角菜单重置恢复。", "”? If network issues occur, you can restore via the top-right menu.")
    text.startsWith("确定要删除覆写规则「") -> text.replace("确定要删除覆写规则「", "Are you sure you want to delete rewrite rule “").replace("」吗？", "”?")
    text.startsWith("已开启 · 每 ") -> text.replace("已开启 · 每 ", "Enabled · Every ").replace(" 小时自动更新", " hours auto-update")
    text.startsWith("已添加到屏蔽规则") -> "Added to block rules"
    text.startsWith("已添加到白名单规则") -> "Added to allowlist rules"
    text.startsWith("已添加 URL 规则") -> "URL rule added"
    text.startsWith("已添加覆写域名") -> "Override domain added"
    text.startsWith("hosts 导入完成：") -> text.replace("hosts 导入完成：新增 ", "hosts import complete: added ").replace(" 条，跳过 ", ", skipped ").replace(" 条", " rules")
    text.startsWith("按域名规则和地址规则分别导出") -> "Export active domain and address rules separately. Domain rules use subscribable TXT; address rules use restorable JSON backups."
    text.startsWith("导出所有订阅导入的当前生效规则") -> "Export all active rules imported from subscriptions"
    text.startsWith("导出所有手动添加的当前生效规则") -> "Export all active manually added rules"
    text.startsWith("合并订阅导入与手动添加的当前生效规则") -> "Merge active rules imported from subscriptions and added manually"
    text.startsWith("导出") && text.contains("当前生效规则") -> text.replace("导出", "Export").replace("当前生效规则", "active rules")
    text.startsWith("确定删除「") && !text.contains("中的全部") -> text.replace("确定删除「", "Delete “").replace("」及其导入的所有规则吗？", "” and all imported rules?")
    text.startsWith("解散「") -> text.replace("解散「", "Dissolve “").replace("」后，组内订阅将移至未分组，不会删除订阅及规则。", "”; subscriptions in the group will move to Ungrouped. Subscriptions and rules will not be deleted.")
    text.startsWith("确定删除「") && text.contains("中的全部") -> text.replace("确定删除「", "Delete all subscriptions and rules in “").replace("」中的全部", "” (").replace(" 个订阅及其规则吗？DNS ", " subscriptions and rules? DNS ").replace(" 个，HTTPS ", ", HTTPS ").replace(" 个。", ".")
    text.startsWith("当前共有 ") -> text.replace("当前共有 ", "There are ")
        .replace(" 条屏蔽规则", " blocked rules")
        .replace(" 条白名单规则", " allowlist rules")
        .replace(" 条 IPv4/IPv6 覆写规则", " IPv4/IPv6 override rules")
        .replace("。DNS 与 HTTPS 检查共用这套域名策略。屏蔽与放行请前往功能中心「黑名单」与「白名单」。", ". DNS and HTTPS inspection share this domain policy. For blocking and allowing, please go to Feature Hub “Blacklist” and “Whitelist”.")
        .replace(" 条 CNAME 覆写规则", " CNAME override rules")
    text.startsWith("仅在 HTTPS 流量检查可解密的 HTTP(S) 请求中生效。") -> text.replace("仅在 HTTPS 流量检查可解密的 HTTP(S) 请求中生效。当前共有 ", "Only effective for HTTP(S) requests decryptable by HTTPS inspection. Currently there are ")
        .replace(" 条 URL 屏蔽规则和 ", " URL block rules and ")
        .replace(" 条 CNAME 覆写规则。屏蔽与放行请前往功能中心「黑名单」与「白名单」。", " CNAME override rules. For blocking and allowing, please go to Feature Hub “Blacklist” and “Whitelist”.")
        .replace(" 条 CNAME 覆写规则。放行请前往功能中心「白名单」。", " CNAME override rules. For allowing, please go to Feature Hub “Whitelist”.")
    text.startsWith("域名规则已关闭，所有域名功能均被禁用。") -> text.replace("域名规则已关闭，所有域名功能均被禁用。当前共有 ", "Domain rules are turned off and all features are disabled. Currently there are ").replace(" 条屏蔽规则", " blocked rules").replace(" 条白名单规则", " allowlist rules").replace(" 条 IPv4/IPv6 覆写规则。", " IPv4/IPv6 override rules.")
    text.startsWith("地址规则已关闭，所有地址规则功能均被禁用。") -> text.replace("地址规则已关闭，所有地址规则功能均被禁用。当前共有 ", "Address rules are turned off and all features are disabled. Currently there are ").replace(" 条 URL 屏蔽规则、", " URL block rules, ").replace(" 条 URL 放行规则和 ", " URL allowlist rules, and ").replace(" 条 URL 屏蔽规则和 ", " URL block rules and ").replace(" 条 CNAME 覆写规则。", " CNAME override rules.")
    text.startsWith("已删除") && text != "已删除" -> text.replace("已删除", "Deleted ")
                .replace("当前范围的全部规则", "all rules in the current scope")
                .replace("请求日志", "request logs")
                .replace("DNS 缓存", "DNS cache")
                .replace("全部规则", "all rules")
    text.endsWith(" 条规则") -> text.removeSuffix(" 条规则") + " rules"
    else -> null
}
