package com.haoze.dnssr.ui.localization

/**
 * 应用设置、日夜模式、主题色、透明度、壁纸背景、出站代理及数据清理本地化词条。
 */
internal fun translateSettingsAndAppearanceExact(text: String): String? = when (text) {
    "清除全部流量记录？" -> "Clear all traffic records?"
    "关闭“通知常驻”只会停止 VPN 未运行时的监控提醒。VPN 正在运行时，系统要求的前台服务通知会继续显示。" -> "Disabling “Persistent notification” stops monitoring reminders only while the VPN is not running. The required foreground-service notification remains while the VPN is running."
    "SOCKS5 通过 UDP ASSOCIATE 转发 UDP。代理应用本身将绕过 DNSSR，防止流量环路。" -> "SOCKS5 forwards UDP through UDP ASSOCIATE. The proxy app itself bypasses DNSSR to prevent traffic loops."
    "已忽略电池优化" -> "Battery optimization ignored"
    "删除壁纸" -> "Delete wallpaper"
    "确定删除这张已添加的壁纸吗？" -> "Delete this added wallpaper?"
    "重置所有新手引导" -> "Reset all onboarding guides"
    "数据清理" -> "Data cleanup"
    "出站代理" -> "Outbound proxy"
    "后台隐藏" -> "Hide in background"
    "IPv6 流量接管" -> "IPv6 traffic handling"
    "自动探测（推荐）" -> "Auto-detect (Recommended)"
    "根据物理网络是否具备公网 IPv6 地址及有效网关路由自动决策；在纯 IPv4 网络下自动关闭 IPv6 虚拟网卡，避免产生连接黑洞" -> "Automatically enable or disable based on physical network IPv6 availability and gateway routes; disables IPv6 on IPv4-only networks to avoid connection black holes"
    "始终开启" -> "Always enable"
    "虚拟网卡始终配置全局 IPv6 地址与路由" -> "Always configure global IPv6 address and routes on the virtual interface"
    "始终禁用" -> "Always disable"
    "仅配置 IPv4 虚拟网卡，强制所有双栈网站走 IPv4 隧道" -> "Configure only IPv4 on the virtual interface, forcing dual-stack sites through IPv4"
    "若在无 IPv6 的 Wi-Fi 下出现豆包、抖音等网站无法打开，请保持“自动探测”或设为“始终禁用”。修改后重新开启服务生效。" -> "If sites like Doubao or Douyin fail on Wi-Fi without IPv6, keep 'Auto-detect' or select 'Always disable'. Restart the service to apply."
    "通知常驻" -> "Persistent notification"
    "忽略电池优化" -> "Ignore battery optimizations"
    "日夜模式" -> "Light and dark mode"
    "主题色配置" -> "Accent color"
    "首页透明度" -> "Home-screen transparency"
    "分别调整首页按钮、选择框与文字的透明度" -> "Adjust the transparency of home buttons, selectors, and text"
    "首页句子" -> "Home messages"
    "通知栏文案" -> "Notification text"
    "分别设置 DNS 服务开启和关闭时的通知栏文案" -> "Set separate notification text for when the DNS service is enabled and disabled"
    "通知栏显示实时速率" -> "Show real-time speed in notification"
    "软件背景" -> "App background"
    "旧版图标" -> "Legacy icon"
    "旧版日志页面" -> "Legacy log page"
    "使用旧版图标" -> "Use legacy icon"
    "使用旧版日志页面" -> "Use legacy log page"
    "启用软件背景" -> "Enable app background"
    "已添加壁纸" -> "Added wallpapers"
    "主题色" -> "Accent color"
    "后台隐藏、通知常驻和电池设置" -> "Background hiding, persistent notifications, and battery settings"
    "将过滤后的流量转发到本地 SOCKS5 或 HTTP 代理" -> "Forward filtered traffic to a local SOCKS5 or HTTP proxy"
    "选择提供本地代理端口的应用。代理应用本身会绕过 DNSSR。" -> "Choose the app that provides the local proxy port. The proxy app itself bypasses DNSSR."
    "启用出站代理功能" -> "Enable outbound proxy"
    "代理应用" -> "Proxy app"
    "选择代理应用" -> "Choose proxy app"
    "正在连接出站代理" -> "Connecting to outbound proxy"
    "开启软件背景" -> "Enable app background"
    "关闭软件背景" -> "Disable app background"
    "使用系统壁纸的动态取色" -> "Use dynamic colors from the system wallpaper"
    "浅色模式" -> "Light mode"
    "深色模式" -> "Dark mode"
    "代理地址仅支持 127.0.0.1 或 ::1" -> "The proxy address must be 127.0.0.1 or ::1"
    "代理端口必须在 1 到 65535 之间" -> "The proxy port must be between 1 and 65535"
    "请选择提供本地代理端口的应用" -> "Choose the app that provides the local proxy port"
    "不能选择 DNSSR 自身作为代理应用" -> "DNSSR itself cannot be selected as the proxy app"
    "所选代理应用未安装" -> "The selected proxy app is not installed"
    "出站代理设置已保存" -> "Outbound proxy settings saved"
    "前往系统电池优化设置" -> "Open system battery optimization settings"
    "已重置所有新手引导" -> "All setup guides reset"
    "液态流体效果" -> "Liquid fluid effect"
    "设置悬浮底栏等组件的液态流体与磨砂折射效果" -> "Configure liquid fluid and frosted refraction effects for components like the bottom bar"
    "启用液态流体效果底栏" -> "Enable liquid fluid bottom bar"
    "为软件底部悬浮栏启用液态流体质感、磨砂光泽与流动光晕效果" -> "Enable liquid fluid texture, frosted sheen, and fluid glow for the floating bottom bar"
    "特别致谢开源项目 KernelSU (tiann/KernelSU) 及其优秀的液态流体与动态悬浮底栏交互设计与代码启发。" -> "Special thanks to open-source project KernelSU (tiann/KernelSU) for inspiring the liquid fluid aesthetic and dynamic floating bottom bar interaction."
    "液态玻璃效果" -> "Liquid glass effect"
    "设置悬浮底栏等组件的液态玻璃与磨砂折射效果" -> "Configure liquid glass and frosted refraction effects for components like the bottom bar"
    "启用液态玻璃效果底栏" -> "Enable liquid glass bottom bar"
    "为软件底部悬浮栏启用液态玻璃质感、磨砂光泽与流动光晕效果" -> "Enable liquid glass texture, frosted sheen, and fluid glow for the floating bottom bar"
    "特别致谢开源项目 KernelSU (tiann/KernelSU) 及其优秀的液态玻璃与动态悬浮底栏交互设计与代码启发。" -> "Special thanks to open-source project KernelSU (tiann/KernelSU) for inspiring the liquid glass aesthetic and dynamic floating bottom bar interaction."
    // 主题色名称
    "鸢尾紫" -> "Iris Purple"
    "睡莲蓝" -> "Water Lily Blue"
    "池水青" -> "Pool Cyan"
    "柳叶绿" -> "Willow Green"
    "暮光赭" -> "Dusk Ochre"
    "罂粟红" -> "Poppy Red"
    "暮霞粉" -> "Sunset Pink"
    "麦穗金" -> "Wheat Gold"
    // 缓存策略与解析模式
    "跟随 DNS TTL" -> "Follow DNS TTL"
    "限制最长缓存时间" -> "Cap maximum TTL"
    "固定缓存时间" -> "Fixed TTL"
    "跟随系统" -> "Follow system"
    // 服务商名称
    "腾讯云" -> "Tencent Cloud"
    "字节跳动" -> "ByteDance"
    "自定义" -> "Custom"
    // 前后台与其他
    "局域网" -> "Local network"
    "绕过局域网" -> "Bypass local network"
    "开启后局域网通信（如文件快传、投屏、NAS 访问等）直接走物理网络，不经过虚拟网卡" -> "When enabled, local network traffic (file quick transfer, screen casting, NAS access, etc.) goes directly through the physical network instead of the VPN interface"
    "若日常使用快传、LocalSend、投屏或访问局域网设备，建议保持开启。修改后重新开启服务生效。" -> "Keep this on if you regularly use quick transfer, LocalSend, screen casting, or access local network devices. Restart the service after changing."
    "前后台行为" -> "Foreground and background behavior"
    "后台隐藏、通知常驻、绕过局域网" -> "Background hiding, persistent notification, LAN bypass"
    "开启" -> "Enable"
    "未选择" -> "Not selected"
    "加载失败" -> "Load failed"
    "两项内容均可留空；留空后对应状态下首页不显示句子。" -> "Both fields can be left empty; the home page will not show a sentence in that state."
    "两项内容均可留空；留空后对应通知栏会使用默认状态文案。" -> "Both fields can be left empty; the notification will use the default status text in that case."
    else -> null
}

internal fun translateSettingsAndAppearancePattern(text: String): String? = when {
    text.startsWith("出站代理不可用 · ") -> text.replace("出站代理不可用 · ", "Outbound proxy unavailable · ")
    text.startsWith("关闭“通知常驻”") -> "Disabling persistent notifications only stops monitoring reminders while the VPN is not running. The required foreground-service notification remains visible while the VPN is running."
    else -> null
}
