// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {windows} from '../models';

export function CaptureWindow(arg1:string):Promise<string>;

export function ConfigureFirewallForLAN(arg1:boolean):Promise<string>;

export function GetCoreServiceStatus():Promise<windows.CoreServiceStatus>;

export function Greet(arg1:string):Promise<string>;

export function InstallAndStartCoreService():Promise<string>;

export function InstallCoreService():Promise<string>;

export function IsAutoStartEnabled():Promise<boolean>;

export function RestartCoreService():Promise<string>;

export function RunEmergencyRestore():Promise<string>;

export function SetAutoStart(arg1:boolean):Promise<boolean>;

export function StartCoreService():Promise<string>;

export function StopCoreService():Promise<string>;

export function UninstallCoreService():Promise<string>;
