// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureWindow(arg1) {
  return window['go']['main']['App']['CaptureWindow'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function RunEmergencyRestore() {
  return window['go']['main']['App']['RunEmergencyRestore']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}
