// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemAccentColor() {
  return window['go']['main']['App']['GetSystemAccentColor']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunEmergencyRestore() {
  return window['go']['main']['App']['RunEmergencyRestore']();
}
