// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureWindow(arg1) {
  return window['go']['main']['App']['CaptureWindow'](arg1);
}

export function GetCoreServiceStatus() {
  return window['go']['main']['App']['GetCoreServiceStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallAndStartCoreService() {
  return window['go']['main']['App']['InstallAndStartCoreService']();
}

export function InstallCoreService() {
  return window['go']['main']['App']['InstallCoreService']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function RestartCoreService() {
  return window['go']['main']['App']['RestartCoreService']();
}

export function RunEmergencyRestore() {
  return window['go']['main']['App']['RunEmergencyRestore']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function StartCoreService() {
  return window['go']['main']['App']['StartCoreService']();
}

export function StopCoreService() {
  return window['go']['main']['App']['StopCoreService']();
}

export function UninstallCoreService() {
  return window['go']['main']['App']['UninstallCoreService']();
}
